const BIRD_CREDITS = {
  "abi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "ahoudori": { artist: "Jlfutari at English Wikipedia", license: "CC BY 2.5" },
  "ajisashi": { artist: "MPF", license: "CC BY-SA 4.0" },
  "akaashishigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "akaerihireashishigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "akaerikaitsuburi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "akagashirasagi": { artist: "Charles Lam", license: "CC SA 1.0" },
  "akagera": { artist: "Gerry Zambonini", license: "CC BY-SA 2.0" },
  "akahara": { artist: "ISAKA Yoji ( cory )[ Recent works / Other works ]", license: "CC BY-SA 3.0" },
  "akahige": { artist: "(c) Wich’yanan L, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "akamashiko": { artist: "Михаил Малышев", license: "CC BY 4.0" },
  "akamozu": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "akashoubin": { artist: "JJ Harrison", license: "CC BY-SA 3.0" },
  "amamiyamashigi": { artist: "Wich’yanan (Jay) Limparungpatthanakij", license: "CC BY 4.0" },
  "amasagi": { artist: "Pedro Lastra", license: "CC BY-SA 2.0" },
  "amatsubame": { artist: "Stuart Price from Hakodate, Japan", license: "CC BY-SA 2.0" },
  "amerikahidori": { artist: "Polinova", license: "CC BY-SA 4.0" },
  "aoashishigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "aobato": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "aobazuku": { artist: "M.Nishimura", license: "CC BY-SA 3.0" },
  "aogera": { artist: "Yasuo Hamashima", license: "CC BY-SA 4.0" },
  "aoji": { artist: "大家好64", license: "CC BY 4.0" },
  "aoshigi": { artist: "(c) Kudaibergen Amirekul, some rights reserved ...", license: "CC BY-SA 4.0" },
  "arisui": { artist: "Бусел В.А.", license: "CC BY-SA 4.0" },
  "atori": { artist: "mmlolek", license: "CC BY 2.0" },
  "ban": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "beniajisashi": { artist: "MPF", license: "CC BY-SA 4.0" },
  "benihiwa": { artist: "Jyrki Salmi from Finland", license: "CC BY-SA 2.0" },
  "benimashiko": { artist: "VLASOV EGOR (egorbirder)", license: "CC BY 4.0" },
  "binzui": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "buppousou": { artist: "Aviceda", license: "CC BY-SA 3.0" },
  "chigohayabusa": { artist: "Shantanu Kuveskar", license: "CC BY-SA 4.0" },
  "chigomozu": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "chishimaugarasu": { artist: "Lisa Hupp/USFWS.", license: "Public domain" },
  "chougenbou": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "chuuhi": { artist: "(c) Анна Васильченко, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "chuusagi": { artist: "Rison Thumboor from Thrissur, India", license: "CC BY 2.0" },
  "chuushakushigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "daisagi": { artist: "Chuck Homler (FocusOnWildlife.Me)", license: "CC BY-SA 4.0" },
  "daishakushigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "daizen": { artist: "Chuck Homler, Focus On Wildlife", license: "CC BY-SA 4.0" },
  "eriguroajisashi": { artist: "Mvbellad", license: "CC BY-SA 4.0" },
  "erimakishigi": { artist: "Tokumi", license: "Public domain" },
  "etopirika": { artist: "Alan D. Wilson", license: "CC BY-SA 3.0" },
  "ezobitaki": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "ezomushikui": { artist: "Gin tonic", license: "Copyrighted free use" },
  "ezoraichou": { artist: "(c) Ilkka Tuunainen, some rights reserved (CC B...", license: "CC BY-SA 4.0" },
  "ezosennyu": { artist: "Юлия (wrrite)", license: "CC BY 4.0" },
  "fukurou": { artist: "Jyrki Salmi from Finland", license: "CC BY-SA 2.0" },
  "gabichou": { artist: "Charles Lam", license: "CC BY-SA 2.0" },
  "ginmukudori": { artist: "Charles Lam", license: "CC BY-SA 2.0" },
  "ginzanmashiko": { artist: "Ron Knight from Seaford, East Sussex, United Ki...", license: "CC BY 2.0" },
  "goisagi": { artist: "ramidos", license: "CC BY 4.0" },
  "gojuukara": { artist: "Isiwal", license: "CC BY-SA 4.0" },
  "hagimashiko": { artist: "M.Nishimura", license: "CC BY-SA 3.0" },
  "haiirochUhi": { artist: "Александр Чегодаев", license: "CC0" },
  "hajirokaitsuburi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "hakkachou": { artist: "Laitche", license: "CC BY-SA 4.0" },
  "hakugan": { artist: "Rhododendrites", license: "CC BY-SA 4.0" },
  "hamashigi": { artist: "Charles Homler d/b/a FocusOnWildlife", license: "CC BY-SA 4.0" },
  "harioamatsubame": { artist: "JJ Harrison", license: "CC BY-SA 4.0" },
  "hashibirogamo": { artist: "JoachimKohler-HB", license: "CC BY-SA 4.0" },
  "hashibutogara": { artist: "Sławek Staszczuk (photoss [AT] hotmail.co.uk)", license: "CC BY-SA 3.0" },
  "herasagi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "herashigi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "hibari": { artist: "User:Diliff", license: "CC BY-SA 3.0" },
  "hibarishigi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "hidorigamo": { artist: "Laitche", license: "CC BY-SA 4.0" },
  "higara": { artist: "Luiz Lapa from Oeiras, Portugal", license: "CC BY 2.0" },
  "hikuina": { artist: "Orban.Balazs", license: "CC BY-SA 4.0" },
  "himeamatsubame": { artist: "Prasan Shrestha", license: "CC BY-SA 4.0" },
  "himekuroumitsubame": { artist: "Joseph Smit", license: "Public domain" },
  "himeu": { artist: "Mike Baird from Morro Bay, USA", license: "CC BY 2.0" },
  "hirenjaku": { artist: "sunjiao", license: "CC BY 4.0" },
  "hishikui": { artist: "Adrian Pingstone", license: "Public domain" },
  "honseiinko": { artist: "danielskatz", license: "CC BY 4.0" },
  "hooaka": { artist: "(c) Griha Hasanov, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "hoojiro": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "hoojirogamo": { artist: "https://www.flickr.com/photos/sbern/", license: "CC BY 2.0" },
  "hoshigarasu": { artist: "Tokumi", license: "Copyrighted free use" },
  "hoshihajiro": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "hoshimukudori": { artist: "PierreSelim", license: "CC BY-SA 3.0" },
  "hototogisu": { artist: "Tisha Mukherjee", license: "CC BY-SA 4.0" },
  "hourokushigi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 4.0" },
  "iijimamushikui": { artist: "孫鋒 林 from Taipei, Taiwan", license: "CC BY-SA 2.0" },
  "ikaru": { artist: "Francesco Veronesi from Italy", license: "CC BY-SA 2.0" },
  "ikaruchidori": { artist: "Sun Jiao (Interaccoonale)", license: "CC BY 4.0" },
  "inuwashi": { artist: "Giles Laurent", license: "CC BY-SA 4.0" },
  "isohiyodori": { artist: "jose maria carretero palacios from jerez de los...", license: "CC BY 2.0" },
  "isoshigi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY 3.0" },
  "isuka": { artist: "Elaine R. Wilson, www.naturespicsonline.com", license: "CC BY-SA 3.0" },
  "iwahibari": { artist: "Paco Gómez from Castellón, Spain", license: "CC BY-SA 2.0" },
  "iwatsubame": { artist: "Delichon_dasypus_-Taiwan-8.jpg: Sin Syue Lideri...", license: "CC BY 2.0" },
  "juuichi": { artist: "Rejaul Karim", license: "CC BY-SA 4.0" },
  "kaitsuburi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "kakesu": { artist: "Luc Viatour", license: "CC BY-SA 3.0" },
  "kakkou": { artist: "Andy  Morffew from Itchen Abbas, Hampshire, UK", license: "CC BY 2.0" },
  "kamome": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "kanadaduru": { artist: "JeffreyGammon", license: "CC BY 4.0" },
  "kanmuriUmisuzume": { artist: "Alastair Rae from London, United Kingdom", license: "CC BY-SA 2.0" },
  "kanmurikaitsuburi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "kanmuriwashi": { artist: "Yathin S Krishnappa", license: "CC BY-SA 3.0" },
  "karaakahara": { artist: "Charles Lam", license: "CC BY-SA 2.0" },
  "karasubato": { artist: "Totti", license: "CC BY-SA 4.0" },
  "karigane": { artist: "Unknown", license: "CC BY-SA 3.0" },
  "kasasagi": { artist: "Rhododendrites", license: "CC BY-SA 4.0" },
  "kashiradaka": { artist: "Gin tonic", license: "CC BY-SA 3.0" },
  "katsuodori": { artist: "Danilo da Castro", license: "CC BY-SA 3.0" },
  "kawaaisa": { artist: "Bengt Nyman from Vaxholm, Sweden", license: "CC BY 2.0" },
  "kawagarasu": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "kawarabato": { artist: "william_stephens", license: "CC BY 4.0" },
  "kawau": { artist: "MPF", license: "CC BY-SA 4.0" },
  "kayakuguri": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "keashinosuri": { artist: "Marton Berntsen", license: "CC BY-SA 4.0" },
  "keimafuri": { artist: "Eliezg", license: "CC BY 3.0" },
  "keri": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "kiashishigi": { artist: "honan4108 on Flickr", license: "CC BY 2.0" },
  "kibashiri": { artist: "caroline legg", license: "CC BY 2.0" },
  "kibitaki": { artist: "Kuribo", license: "CC BY-SA 2.0" },
  "kiji": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "kikuitadaki": { artist: "Francis C. Franklin", license: "CC BY-SA 3.0" },
  "kimayuhoojiro": { artist: "Devonpike", license: "CC BY-SA 3.0" },
  "kimayumushikui": { artist: "Frank Vassen from Brussels, Belgium", license: "CC BY 2.0" },
  "kinbato": { artist: "JJ Harrison", license: "CC BY-SA 4.0" },
  "kinkurohajiro": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "kirenjaku": { artist: "Tatiana Bulyonkova from Novosibirsk, Russia", license: "CC BY-SA 2.0" },
  "kisekirei": { artist: "Herwig Winter", license: "CC BY-SA 4.0" },
  "koahoudori": { artist: "DickDaniels (http://theworldbirds.org/)", license: "CC BY-SA 3.0" },
  "koajisashi": { artist: "PetroKaterynych", license: "CC BY 4.0" },
  "koaoashishigi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "kobuhakuchou": { artist: "Sanchezn", license: "CC BY-SA 3.0" },
  "kochidori": { artist: "Zeynel Cebeci", license: "CC BY-SA 4.0" },
  "kogamo": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "kogara": { artist: "Francis C. Franklin", license: "CC BY-SA 3.0" },
  "kogera": { artist: "Laitche", license: "CC BY-SA 4.0" },
  "kohakuchou": { artist: "Maga-chan", license: "CC BY-SA 2.5" },
  "kohooaka": { artist: "Andreas Trepte", license: "CC BY-SA 4.0" },
  "koikaru": { artist: "Zinogre", license: "CC BY-SA 4.0" },
  "kojukei": { artist: "Sun Jiao (Interaccoonale)", license: "CC BY-SA 4.0" },
  "kojurin": { artist: "VLASOV EGOR (egorbirder)", license: "CC BY 4.0" },
  "kokugan": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "kokumarugarasu": { artist: "christoph_moning", license: "CC BY 4.0" },
  "komadori": { artist: "Alnus", license: "CC BY-SA 3.0" },
  "komimizuku": { artist: "Sumeet Moghe", license: "CC BY-SA 4.0" },
  "komukudori": { artist: "M.Nishimura", license: "CC BY-SA 3.0" },
  "konohazuku": { artist: "Frank Vassen from Brussels, Belgium", license: "CC BY 2.0" },
  "koorigamo": { artist: "Wolfgang Wander", license: "CC BY-SA 3.0" },
  "koruri": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "kosamebitaki": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "koshiakatsubame": { artist: "Shantanu Kuveskar", license: "CC BY-SA 4.0" },
  "kounotori": { artist: "Unknown", license: "CC BY 2.1 jp" },
  "kouraiuguisu": { artist: "J.M.Garg", license: "CC BY 3.0" },
  "koyoshikiri": { artist: "Ariefrahman", license: "CC BY-SA 3.0" },
  "kuina": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "kumagera": { artist: "Dion Art", license: "CC BY-SA 4.0" },
  "kuroajisashi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "kuroashiahoudori": { artist: "Original uploader was Jlfutari at en.wikipedia", license: "CC BY-SA 3.0" },
  "kuroduru": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "kurogamo": { artist: "Richard Crossley", license: "CC BY-SA 3.0" },
  "kuroji": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "kurosagi": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 4.0" },
  "kurotsugumi": { artist: "(c) Lawrence Hylton, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "kurotsuraherasagi": { artist: "Cp9asngf", license: "CC BY-SA 3.0" },
  "kusashigi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "kyoujoshigi": { artist: "Chuck Homler d/b/a Focus On Wildlife", license: "CC BY-SA 4.0" },
  "magamo": { artist: "This picture was realized by Richard Bartz by u...", license: "CC BY-SA 2.5" },
  "magan": { artist: "Frank Schulenburg", license: "CC BY-SA 4.0" },
  "mahiwa": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "makinosennyu": { artist: "Tokumi Ohsaka", license: "CC0" },
  "mamichajinai": { artist: "Robert tdc", license: "CC BY-SA 2.0" },
  "mamijiro": { artist: "JJ Harrison", license: "CC BY-SA 4.0" },
  "mamijirotahibari": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY 3.0" },
  "manaduru": { artist: "Spaceaero2", license: "CC BY-SA 3.0" },
  "mebosomushikui": { artist: "(c) Jan Ebr, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "medaichidori": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY 3.0" },
  "meguro": { artist: "Tomohide shimura", license: "CC BY-SA 4.0" },
  "mifuuzura": { artist: "Tisha Mukherjee", license: "CC BY-SA 4.0" },
  "mikoaisa": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "mimikaitsuburi": { artist: "Ekaterina Chernetsova (Papchinskaya) from Saint...", license: "CC BY 2.0" },
  "minamitoratsugumi": { artist: "Charles Lam from Hong Kong, China", license: "CC BY-SA 2.0" },
  "misago": { artist: "Chuck Homler / Focus On Wildlife", license: "CC BY-SA 4.0" },
  "misosazai": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "mitsuyubikamome": { artist: "Yathin S Krishnappa", license: "CC BY-SA 3.0" },
  "miyakodori": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "miyamagarasu": { artist: "Hobbyfotowiki", license: "CC0" },
  "miyamahoojiro": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "miyubishigi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "mizogoi": { artist: "https://www.flickr.com/photos/ken_san/", license: "CC BY-SA 2.0" },
  "mugimaki": { artist: "Wang.QG", license: "CC BY 4.0" },
  "munaguro": { artist: "Bering Land Bridge National Preserve", license: "CC BY 2.0" },
  "muneakatahibari": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "murasakisagi": { artist: "Mahmadanesh", license: "CC BY 4.0" },
  "nabeduru": { artist: "Alastair Rae from London, United Kingdom", license: "CC BY-SA 2.0" },
  "nishiojiRobitaki": { artist: "Nppgrandmeadow", license: "CC BY-SA 4.0" },
  "nobitaki": { artist: "Derek Keats from South Africa", license: "CC BY-SA 2.0" },
  "nogoma": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "noguchigera": { artist: "Amateras7777", license: "CC BY-SA 4.0" },
  "nojiko": { artist: "Koolah (talk)", license: "CC BY-SA 3.0" },
  "nyuunaIsuzume": { artist: "Tisha Mukherjee", license: "CC BY-SA 4.0" },
  "obashigi": { artist: "Original: tcager; this edit: User:MPF", license: "CC0" },
  "oguroshigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "ojirotounen": { artist: "Andrey Gulivanov", license: "CC BY 2.0" },
  "okayoshigamo": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "onaga": { artist: "J. Patrick Fischer", license: "CC BY-SA 3.0" },
  "onagagamo": { artist: "J.M.Garg", license: "CC BY-SA 3.0" },
  "ooakagera": { artist: "Alastair Rae", license: "CC BY-SA 3.0" },
  "ooban": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "oohakuchou": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "oohamu": { artist: "Bengt Nyman from Vaxholm, Sweden", license: "CC BY 2.0" },
  "oohashishigi": { artist: "Mike Baird from Morro Bay, USA", license: "CC BY 2.0" },
  "oojishigi": { artist: "Jason Girvan", license: "CC BY-SA 3.0" },
  "oojurin": { artist: "caroline legg", license: "CC BY 2.0" },
  "ookonohazuku": { artist: "Amateras7777", license: "CC BY-SA 4.0" },
  "oomashiko": { artist: "M.Nishimura", license: "CC BY-SA 3.0" },
  "oomizunagidori": { artist: "Kanachoro", license: "CC BY-SA 3.0" },
  "oomozu": { artist: "Andrey Gulivanov", license: "CC BY 2.0" },
  "ooruri": { artist: "Tokumi Ohsaka", license: "Public domain" },
  "oosegurokamome": { artist: "E-190", license: "CC BY-SA 3.0" },
  "oosekka": { artist: "WJMcBride", license: "CC BY-SA 3.0" },
  "oosorihashishigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "ooyoshigoi": { artist: "Francesco Veronesi from Italy", license: "CC BY-SA 2.0" },
  "ooyoshikiri": { artist: "J.M.Garg", license: "CC BY-SA 3.0" },
  "oriigara": { artist: "Julia Wittmann", license: "CC BY 4.0" },
  "oshidori": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "ouchuu": { artist: "Swardeepak", license: "CC BY-SA 4.0" },
  "raichou": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "renkaku": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "ruribitaki": { artist: "M.Nishimura", license: "CC BY-SA 3.0" },
  "rurikakesu": { artist: "Materialscientist", license: "CC BY-SA 3.0" },
  "ryuukyuukonohazuku": { artist: "WeitingLiu (weitingliu)", license: "CC BY 4.0" },
  "ryuukyuusanshoukui": { artist: "Hisagi", license: "CC BY-SA 4.0" },
  "ryuukyuuyoshigoi": { artist: "Shantanu Kuveskar", license: "CC BY-SA 4.0" },
  "samebitaki": { artist: "https://www.flickr.com/photos/79492850@N00/", license: "CC BY 2.0" },
  "sankanogoi": { artist: "Francesco Veronesi from Italy", license: "CC BY-SA 2.0" },
  "sankouchou": { artist: "Pokopong", license: "CC BY-SA 3.0" },
  "sanshokui": { artist: "Ariefrahman", license: "CC BY-SA 3.0" },
  "saruhamashigi": { artist: "Imran Shah from Islamabad, Pakistan", license: "CC BY-SA 2.0" },
  "sasagoi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "segurokakkou": { artist: "Creepanta", license: "CC BY-SA 4.0" },
  "segurokamome": { artist: "Rhododendrites", license: "CC BY-SA 4.0" },
  "segurosekirei": { artist: "nubobo from Iwata, Shizuoka, Japan", license: "CC BY 2.0" },
  "seitakashigi": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "sekka": { artist: "Alexis Lours", license: "CC BY 4.0" },
  "sendaimushikui": { artist: "孫鋒 林", license: "CC BY-SA 2.0" },
  "shijuukaragaN": { artist: "Roy Lowe/U.S. Fish and Wildlife Service", license: "Public domain" },
  "shimaaji": { artist: "YedidyaPopper", license: "CC BY 4.0" },
  "shimaaoji": { artist: "Manshanta Ghimire", license: "CC BY-SA 4.0" },
  "shimafukurou": { artist: "Tokumi", license: "Public domain" },
  "shimagoma": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "shimakinpara": { artist: "Charles J. Sharp", license: "CC BY-SA 4.0" },
  "shimasennyu": { artist: "Tokumi Ohsaka", license: "CC0" },
  "shime": { artist: "Mikils", license: "CC BY-SA 4.0" },
  "shinorigamo": { artist: "Chuck Homler d/b/a Focus On Wildlife", license: "CC BY-SA 4.0" },
  "shirakobato": { artist: "stevem4560", license: "CC BY 4.0" },
  "shirochidori": { artist: "Original: Davidvraju, edit: MPF", license: "CC BY-SA 4.0" },
  "shiroerioohamu": { artist: "USFWSAlaska", license: "Public domain" },
  "shirogashira": { artist: "Charles Lam", license: "CC BY-SA 2.0" },
  "shirohara": { artist: "Francesco Veronesi from Italy", license: "CC BY-SA 2.0" },
  "shiroharakuina": { artist: "JJ Harrison (https://tiny.jjharrison.com.au/t/z...", license: "CC BY-SA 4.0" },
  "shirokamome": { artist: "Alastair Rae from London, UK", license: "CC BY-SA 2.0" },
  "shoudoutsubame": { artist: "Andy  Morffew from Itchen Abbas, Hampshire, UK", license: "CC BY 2.0" },
  "sorihashiseitakashigi": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "sorihashishigi": { artist: "Birds of Gilgit-Baltistan", license: "CC BY-SA 2.0" },
  "soushichou": { artist: "Dibyendu Ash", license: "CC BY-SA 3.0" },
  "suzugamo": { artist: "Chuck Homler d/b/a Focus On Wildlife", license: "CC BY-SA 4.0" },
  "tageri": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "tahibari": { artist: "Zeynel Cebeci", license: "CC BY-SA 4.0" },
  "tairikukiji": { artist: "Peter OConnor aka anemoneprojectors", license: "CC BY-SA 2.0" },
  "takabushigi": { artist: "Abdul Momin", license: "CC BY-SA 4.0" },
  "tamashigi": { artist: "Bernard DUPONT from FRANCE", license: "CC BY-SA 2.0" },
  "tanchou": { artist: "Alastair Rae from London, United Kingdom", license: "CC BY-SA 2.0" },
  "tashigi": { artist: "TRinaud", license: "CC BY 4.0" },
  "toki": { artist: "belvedere04", license: "CC BY 4.0" },
  "tomoegamo": { artist: "Sarefo", license: "CC BY-SA 4.0" },
  "torafuzuku": { artist: "Francesco Veronesi from Italy", license: "CC BY-SA 2.0" },
  "toratsugumi": { artist: "Paladitya", license: "CC BY-SA 4.0" },
  "tounen": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 4.0" },
  "touzokukamome": { artist: "Patrick Coin (Patrick Coin)", license: "CC BY-SA 2.5" },
  "tree_abemaki": { artist: "Velela", license: "Public domain" },
  "tree_aburachan": { artist: "Imuzak", license: "Public domain" },
  "tree_akagashi": { artist: "松岡明芳", license: "CC BY-SA 3.0" },
  "tree_akamatsu": { artist: "harum.koh from Kobe city, Japan", license: "CC BY-SA 2.0" },
  "tree_akamegashiwa": { artist: "Daderot", license: "CC0" },
  "tree_akashide": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_akebi": { artist: "Kenraiz, Krzysztof Ziarnek", license: "CC BY-SA 4.0" },
  "tree_akinire": { artist: "SAEI wowfdoao MMOU", license: "CC0" },
  "tree_aodamo": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_aogiri": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_aohada": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_aoki": { artist: "Mitzi.humphrey", license: "CC BY-SA 4.0" },
  "tree_arakashi": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_asada": { artist: "belvedere04", license: "CC BY 4.0" },
  "tree_asebi": { artist: "James St. John", license: "CC BY 2.0" },
  "tree_asunaro": { artist: "Unknown", license: "CC BY 4.0" },
  "tree_awabuki": { artist: "Krzysztof Ziarnek, Kenraiz", license: "CC BY-SA 4.0" },
  "tree_azukinashi": { artist: "Bostonian13", license: "CC BY-SA 3.0" },
  "tree_azumashakunage": { artist: "Sgerbic", license: "CC BY-SA 4.0" },
  "tree_bakkoyanagi": { artist: "Dmitry Makeev", license: "CC BY-SA 4.0" },
  "tree_bodaiju": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_buna": { artist: "Kingfiser", license: "CC BY-SA 4.0" },
  "tree_chidorinoki": { artist: "Bruce Marlin", license: "CC BY-SA 3.0" },
  "tree_dakekamba": { artist: "Krzysztof Golik", license: "CC BY-SA 4.0" },
  "tree_dankoubai": { artist: "Chhe (talk)", license: "Public domain" },
  "tree_doronoki": { artist: "あおもりくま（Aomorikuma）", license: "CC BY-SA 3.0" },
  "tree_edohigan": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_egonoki": { artist: "Krzysztof Golik", license: "CC BY-SA 4.0" },
  "tree_enju": { artist: "Ladislav Luppa", license: "CC BY-SA 4.0" },
  "tree_enoki": { artist: "JMK", license: "CC BY-SA 4.0" },
  "tree_ezomatsu": { artist: "cogito ergo imago from Rumson, NJ", license: "CC BY-SA 2.0" },
  "tree_fuji": { artist: "Forest and Kim Starr", license: "CC BY 3.0 us" },
  "tree_gakuajisai": { artist: "Jules Verne Times Two", license: "CC BY-SA 4.0" },
  "tree_gamazumi": { artist: "Cossey25", license: "CC BY-SA 4.0" },
  "tree_gekkeiju": { artist: "Forest and Kim Starr", license: "CC BY 3.0 us" },
  "tree_gonzui": { artist: "Jens Petersen", license: "CC BY 2.5" },
  "tree_goyoumatsu": { artist: "そらみみ", license: "CC BY-SA 4.0" },
  "tree_goyoutsutsuji": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_hainoki": { artist: "阿橋 HQ", license: "CC BY-SA 2.0" },
  "tree_hakoneutsugi": { artist: "peganum from Small Dole, England", license: "CC BY-SA 2.0" },
  "tree_hakusanshakunage": { artist: "Σ64", license: "CC BY 3.0" },
  "tree_hakuunboku": { artist: "Chhe (talk)", license: "Public domain" },
  "tree_hamanasu": { artist: "dalgial", license: "CC BY-SA 3.0" },
  "tree_hanaikada": { artist: "peganum from Henfield, England", license: "CC BY-SA 2.0" },
  "tree_hanamizuki": { artist: "Photo by David J. Stang", license: "CC BY-SA 4.0" },
  "tree_hananoki": { artist: "kazunari abe", license: "CC BY-SA 3.0" },
  "tree_hannoki": { artist: "Unknown", license: "CC BY 4.0" },
  "tree_harienju": { artist: "Vera Buhl", license: "CC BY-SA 3.0" },
  "tree_harigiri": { artist: "Sten Porse", license: "CC BY-SA 3.0" },
  "tree_harunire": { artist: "Stavast22", license: "CC BY-SA 4.0" },
  "tree_hashibami": { artist: "Aroche", license: "CC BY-SA 3.0" },
  "tree_hashidoi": { artist: "Cossey25", license: "CC BY-SA 4.0" },
  "tree_hauchiwakaede": { artist: "A. Barra", license: "CC BY 3.0" },
  "tree_hazenoki": { artist: "Syced", license: "CC0" },
  "tree_hiiragi": { artist: "Photo by and (c)2007 Derek Ramsey (Ram-Man)", license: "CC BY-SA 2.5" },
  "tree_himarayasugi": { artist: "Andrey Zharkikh from Salt Lake City, USA", license: "CC BY 2.0" },
  "tree_himekouzo": { artist: "Magnus Manske", license: "CC BY-SA 2.5" },
  "tree_himeshara": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_hinoki": { artist: "Unknown", license: "CC BY 4.0" },
  "tree_hisakaki": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_hitotsubakaede": { artist: "E-190", license: "CC BY-SA 3.0" },
  "tree_hitotsubatago": { artist: "Cossey25", license: "CC BY-SA 4.0" },
  "tree_hoonoki": { artist: "PtrQs", license: "CC BY-SA 4.0" },
  "tree_horutonoki": { artist: "Jidanni", license: "CC BY-SA 4.0" },
  "tree_ibotanoki": { artist: "Portraitlady4306", license: "Public domain" },
  "tree_ichii": { artist: "Photo (c)2007 Derek Ramsey (Ram-Man)", license: "CC BY-SA 2.5" },
  "tree_ichiigashi": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_ichou": { artist: "Kevmin", license: "CC BY-SA 4.0" },
  "tree_iigiri": { artist: "Henryhartley at English Wikipedia", license: "CC BY-SA 3.0" },
  "tree_inubiwa": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_inubuna": { artist: "Σ64", license: "CC BY 3.0" },
  "tree_inumaki": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_inushide": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_inutsuge": { artist: "Borlawmensaorkong", license: "CC BY-SA 3.0" },
  "tree_inuzakura": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_irohamomiji": { artist: "Cossey25", license: "CC BY-SA 4.0" },
  "tree_isunoki": { artist: "さかおり", license: "CC BY 4.0" },
  "tree_itayakaede": { artist: "Crusier", license: "CC BY-SA 3.0" },
  "tree_kagonoki": { artist: "Keisotyo", license: "CC BY-SA 4.0" },
  "tree_kajinoki": { artist: "Photo by and (c)2006 Derek Ramsey (Ram-Man).  L...", license: "CC BY-SA 3.0" },
  "tree_kakinoki": { artist: "Benjamín Núñez González", license: "CC BY-SA 4.0" },
  "tree_kakuremino": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_kamatsuka": { artist: "Daderot", license: "Public domain" },
  "tree_kanamemochi": { artist: "そらみみ (Soramimi)", license: "CC BY-SA 4.0" },
  "tree_kanboku": { artist: "Hladac", license: "CC BY-SA 4.0" },
  "tree_kanhizakura": { artist: "Forest and Kim Starr", license: "CC BY 3.0 us" },
  "tree_karamatsu": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_karatachi": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_kashiwa": { artist: "Flynnbar at English Wikipedia", license: "CC BY 2.5" },
  "tree_kasumizakura": { artist: "掬茶", license: "CC BY-SA 4.0" },
  "tree_katsura": { artist: "Photo by David J. Stang", license: "CC BY-SA 4.0" },
  "tree_kaya": { artist: "AraucariaHeterophylla", license: "CC BY 4.0" },
  "tree_keyaki": { artist: "池田正樹 (talk)masaki ikeda", license: "Public domain" },
  "tree_keyamahannoki": { artist: "Sten Porse", license: "CC BY-SA 3.0" },
  "tree_kibushi": { artist: "E-190", license: "CC BY-SA 3.0" },
  "tree_kihada": { artist: "Crusier", license: "CC BY-SA 3.0" },
  "tree_kinmokusei": { artist: "Sanddiea Zhumm", license: "CC BY-SA 4.0" },
  "tree_kiri": { artist: "Magnus Manske", license: "CC BY-SA 3.0" },
  "tree_kizuta": { artist: "Qwert1234", license: "Public domain" },
  "tree_kobushi": { artist: "Jean-Pol GRANDMONT", license: "CC BY 3.0" },
  "tree_kohauchiwakaede": { artist: "pakku", license: "CC BY 3.0" },
  "tree_kokusagi": { artist: "Bruce Marlin", license: "CC BY-SA 3.0" },
  "tree_konara": { artist: "Michael Wolf", license: "CC BY-SA 3.0" },
  "tree_koshiabura": { artist: "あおもりくま（Aomorikuma）", license: "CC BY-SA 3.0" },
  "tree_kouyamaki": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_kuchinashi": { artist: "Forest and Kim Starr", license: "CC BY 3.0 us" },
  "tree_kumanomizuki": { artist: "Kirichenko N, Triberti P, Kobayashi S, Hirowata...", license: "CC BY 4.0" },
  "tree_kumashide": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_kunugi": { artist: "Daderot", license: "Public domain" },
  "tree_kuri": { artist: "Abrahami", license: "CC BY-SA 3.0" },
  "tree_kurobe": { artist: "Kikuko Nakayama", license: "CC BY-SA 2.0" },
  "tree_kuromatsu": { artist: "Forest and Kim Starr", license: "CC BY 3.0 us" },
  "tree_kuromoji": { artist: "E-190", license: "CC BY-SA 3.0" },
  "tree_kusagi": { artist: "Marija Gajić", license: "CC BY-SA 4.0" },
  "tree_kusunoki": { artist: "Photo by David J. Stang", license: "CC BY-SA 4.0" },
  "tree_maguwa": { artist: "Jaknouse", license: "CC BY 3.0" },
  "tree_mansaku": { artist: "Agnieszka Kwiecień, Nova", license: "CC BY-SA 4.0" },
  "tree_marubachishanoki": { artist: "M108t", license: "CC BY 4.0" },
  "tree_marubahagi": { artist: "Dalgial", license: "CC BY-SA 3.0" },
  "tree_marubanoki": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_masaki": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_matatabi": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_matebashii": { artist: "No machine-readable author provided. Koba-chan ...", license: "CC BY 2.5" },
  "tree_mayumi": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_megi": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_megusurinoki": { artist: "Robin Stott", license: "CC BY-SA 2.0" },
  "tree_metasekoia": { artist: "Humoyun Mehridinov", license: "CC BY-SA 4.0" },
  "tree_mitsubaakebi": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_mitsubatsutsuji": { artist: "些細な日常", license: "CC BY-SA 4.0" },
  "tree_mitsudekaede": { artist: "Jean-Pol GRANDMONT", license: "CC BY 3.0" },
  "tree_mizuki": { artist: "Nmspec", license: "CC BY-SA 4.0" },
  "tree_mizume": { artist: "Bostonian13", license: "CC BY-SA 3.0" },
  "tree_mizunara": { artist: "Kinori", license: "CC0" },
  "tree_mochinoki": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_mokkoku": { artist: "Cossey25", license: "CC BY-SA 4.0" },
  "tree_mokuren": { artist: "Fanghong", license: "CC BY-SA 3.0" },
  "tree_momi": { artist: "No machine-readable author provided. Inti-sol~c...", license: "CC BY-SA 3.0" },
  "tree_momijiichigo": { artist: "えだ2", license: "CC BY-SA 4.0" },
  "tree_mube": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_mukunoki": { artist: "BDTeaman", license: "CC BY 4.0" },
  "tree_mukuroji": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_murasaki_shikibu": { artist: "No machine-readable author provided. Koba-chan ...", license: "CC BY 2.5" },
  "tree_nagi": { artist: "Hongshoum Doiar Kingz", license: "CC BY-SA 4.0" },
  "tree_nanakamado": { artist: "Mintleaf", license: "Public domain" },
  "tree_nanten": { artist: "Dominicus Johannes Bergsma", license: "CC BY-SA 4.0" },
  "tree_natsugumi": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_natsutsubaki": { artist: "Photo by and (c)2007 Derek Ramsey (Ram-Man)", license: "GFDL 1.2" },
  "tree_nawashirogumi": { artist: "Forest and Kim Starr", license: "CC BY 3.0 us" },
  "tree_nejiki": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_nekoyanagi": { artist: "‘Uncle Carl’ (カールおじさん).", license: "CC BY-SA 3.0" },
  "tree_nemunoki": { artist: "Σ64", license: "CC BY 3.0" },
  "tree_nezumimochi": { artist: "Cossey25", license: "CC BY-SA 4.0" },
  "tree_nezumisashi": { artist: "Dalgial", license: "CC BY-SA 3.0" },
  "tree_nishikigi": { artist: "Matt Lavin from Bozeman, Montana, USA", license: "CC BY-SA 2.0" },
  "tree_niwatoko": { artist: "Photo by and (c)2006 Derek Ramsey (Ram-Man).  L...", license: "CC BY-SA 3.0" },
  "tree_nobudou": { artist: "Unknown", license: "CC BY-SA 3.0" },
  "tree_noibara": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_noriutsugi": { artist: "Dominicus Johannes Bergsma", license: "CC BY-SA 3.0" },
  "tree_nurude": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_ogatamanoki": { artist: "Júlio Reis", license: "CC BY-SA 3.0" },
  "tree_ohyou": { artist: "Ptelea at English Wikipedia", license: "Public domain" },
  "tree_onigurumi": { artist: "Borealis55", license: "Public domain" },
  "tree_oobayashabushi": { artist: "Rudolphous", license: "CC BY-SA 4.0" },
  "tree_ooitayameigetsu": { artist: "Jamain", license: "CC BY-SA 3.0" },
  "tree_ookamenoki": { artist: "Ka23 13", license: "CC BY-SA 4.0" },
  "tree_oomomiji": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_ooshimazakura": { artist: "SLIMHANNYA", license: "CC BY-SA 4.0" },
  "tree_ooyamarenge": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_ooyamazakura": { artist: "Kingfiser", license: "CC BY-SA 4.0" },
  "tree_otokoyouzome": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_rinboku": { artist: "Keisotyo", license: "CC BY-SA 4.0" },
  "tree_ryoubu": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_saikachi": { artist: "Kurt Stüber [1]", license: "CC BY-SA 3.0" },
  "tree_sakaki": { artist: "‘Uncle Carl’ (カールおじさん).", license: "CC BY-SA 3.0" },
  "tree_sangoju": { artist: "George E. Koronaios", license: "CC BY-SA 2.0" },
  "tree_sanshou": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_sanshuyu": { artist: "Dalgial", license: "CC BY-SA 3.0" },
  "tree_sarusuberi": { artist: "John Robert McPherson", license: "CC0" },
  "tree_sarutoriibara": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_satsuki": { artist: "William Coville", license: "CC BY-SA 4.0" },
  "tree_sawafutagi": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_sawara": { artist: "Rhododendrites", license: "CC BY-SA 4.0" },
  "tree_sawashiba": { artist: "Σ64", license: "CC BY 4.0" },
  "tree_sendan": { artist: "François Delonnay", license: "CC BY-SA 4.0" },
  "tree_sharinbai": { artist: "Frank Schulenburg", license: "CC BY-SA 3.0" },
  "tree_shidareyanagi": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_shikimi": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_shimotsuke": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_shinanoki": { artist: "三上 勝生", license: "CC BY-SA 2.1 jp" },
  "tree_shirabiso": { artist: "WeeJeeVee", license: "CC BY-SA 4.0" },
  "tree_shirakaba": { artist: "Unknown", license: "CC BY-SA 2.0" },
  "tree_shirakashi": { artist: "Dalgial", license: "CC BY-SA 3.0" },
  "tree_shiraki": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_shirodamo": { artist: "Jjw", license: "CC BY-SA 4.0" },
  "tree_shiroyanagi": { artist: "Dalgial", license: "CC BY-SA 3.0" },
  "tree_sudajii": { artist: "Kugel~commonswiki", license: "CC BY-SA 4.0" },
  "tree_sugi": { artist: "Yercaud-elango", license: "CC BY-SA 4.0" },
  "tree_suikazura": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_suzukakenoki": { artist: "ChrisInMilton", license: "CC BY-SA 4.0" },
  "tree_tabunoki": { artist: "No machine-readable author provided. Gondahara ...", license: "CC BY-SA 3.0" },
  "tree_taisanboku": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_tamushiba": { artist: "Megan Hansen from Portland, OR, US", license: "CC BY-SA 2.0" },
  "tree_taniutsugi": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_taranoki": { artist: "Kingfiser", license: "CC BY-SA 4.0" },
  "tree_tarayou": { artist: "This photo has been taken by Matthieu Sontag (U...", license: "CC BY-SA 3.0" },
  "tree_teikakazura": { artist: "M108t", license: "CC BY 4.0" },
  "tree_tobera": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_tochinoki": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_todomatsu": { artist: "663highland", license: "CC BY 2.5" },
  "tree_toneriko": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_toukaede": { artist: "Abrahami", license: "CC BY-SA 3.0" },
  "tree_tsuga": { artist: "Sten Porse", license: "CC BY-SA 3.0" },
  "tree_tsuge": { artist: "Sten Porse", license: "CC BY-SA 3.0" },
  "tree_tsukubaneutsugi": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_tsunohashibami": { artist: "M.S. del., J.N.Fitch lith.", license: "Public domain" },
  "tree_tsuribana": { artist: "A. Barra", license: "CC BY 3.0" },
  "tree_tsuruumemodoki": { artist: "Chris Rycroft", license: "CC BY 2.0" },
  "tree_tsuta": { artist: "Kingfiser", license: "CC BY-SA 4.0" },
  "tree_tsutaurushi": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_ubamegashi": { artist: "Ian Alexander", license: "CC BY-SA 4.0" },
  "tree_udaikamba": { artist: "Tournasol7", license: "CC BY-SA 3.0" },
  "tree_uguisukagura": { artist: "harum.koh from Kobe city, Japan", license: "CC BY-SA 2.0" },
  "tree_ume": { artist: "Kakidai", license: "CC BY-SA 3.0" },
  "tree_umemodoki": { artist: "Krzysztof Ziarnek, Kenraiz", license: "CC BY-SA 4.0" },
  "tree_urajirogashi": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_urihadakaede": { artist: "Liné1", license: "CC BY-SA 3.0" },
  "tree_utsugi": { artist: "Marija Gajić", license: "CC BY-SA 4.0" },
  "tree_uwamizuzakura": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "tree_yabudemari": { artist: "Famartin", license: "CC BY-SA 4.0" },
  "tree_yabunikkei": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_yabutsubaki": { artist: "些細な日常", license: "CC BY-SA 4.0" },
  "tree_yachidamo": { artist: "Herman, D.E., et al. North Dakota tree handbook...", license: "Public domain" },
  "tree_yamaajisai": { artist: "Michele Dorsey Walfred", license: "CC BY 2.0" },
  "tree_yamaboushi": { artist: "Mohamed Rezk", license: "CC BY-SA 3.0" },
  "tree_yamabudou": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_yamabuki": { artist: "Simon A. Eugster", license: "CC BY-SA 4.0" },
  "tree_yamaguwa": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "tree_yamahagi": { artist: "user:Miya.m", license: "CC BY-SA 3.0" },
  "tree_yamahaze": { artist: "harum.koh from Kobe city, Japan", license: "CC BY-SA 2.0" },
  "tree_yamamomiji": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_yamamomo": { artist: "‘Uncle Carl’ (カールおじさん).", license: "CC BY-SA 3.0" },
  "tree_yamatsutsuji": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_yamaukogi": { artist: "Mason Brock (Masebrock)", license: "Public domain" },
  "tree_yamaurushi": { artist: "Dalgial", license: "CC BY-SA 3.0" },
  "tree_yamazakura": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "tree_yashabushi": { artist: "Michael Wolf", license: "CC BY-SA 3.0" },
  "tree_yatsude": { artist: "ChrisInMilton", license: "CC BY-SA 4.0" },
  "tree_yukitsubaki": { artist: "Qwert1234", license: "CC BY-SA 3.0" },
  "tree_yurinoki": { artist: "Hladac", license: "CC BY-SA 4.0" },
  "tree_yuzuriha": { artist: "小石川人晃", license: "CC BY-SA 4.0" },
  "tree_zakuro": { artist: "CaNeCoRsO137", license: "CC BY-SA 4.0" },
  "tree_zumi": { artist: "W.carter", license: "CC BY-SA 4.0" },
  "tsubamechidori": { artist: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0" },
  "tsukushigamo": { artist: "DickDaniels (http://theworldbirds.org/)", license: "CC BY-SA 3.0" },
  "tsumenagahoojiro": { artist: "Ómar Runólfsson", license: "CC BY 2.0" },
  "tsumenagasekirei": { artist: "Frebeck", license: "CC BY-SA 3.0" },
  "tsurisugara": { artist: "Martin Mecnarowski (http://www.photomecan.eu/)", license: "CC BY-SA 3.0" },
  "tsurushigi": { artist: "Hari K Patibanda", license: "CC BY 2.0" },
  "tsutsudori": { artist: "Aviceda", license: "CC BY-SA 3.0" },
  "uchiyamasennyu": { artist: "(c) Andrew Bazdyrev, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "umiaisa": { artist: "Needsmoreritalin", license: "CC BY-SA 4.0" },
  "umigarasu": { artist: "Andreas Trepte", license: "CC BY-SA 2.5" },
  "umineko": { artist: "Unknown", license: "CC BY-SA 3.0" },
  "umisuzume": { artist: "Eric Ellingson", license: "CC BY 2.0" },
  "umiu": { artist: "YCCHEN TW", license: "CC BY-SA 4.0" },
  "uso": { artist: "Francis Franklin", license: "CC BY-SA 3.0" },
  "utou": { artist: "Tokumi", license: "Copyrighted free use" },
  "uzura": { artist: "Ingrid Taylar", license: "CC BY 2.0" },
  "uzurashigi": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "washikamome": { artist: "Drfred55", license: "CC BY-SA 3.0" },
  "watarigarasu": { artist: "Accipiter (R. Altenkamp, Berlin)", license: "CC BY-SA 3.0" },
  "yaIrochou": { artist: "Alnus", license: "CC BY-SA 3.0" },
  "yabusame": { artist: "(c) Rejoice Gassah, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "yamadori": { artist: "Stavenn", license: "CC BY-SA 3.0" },
  "yamagara": { artist: "Laitche", license: "CC BY-SA 4.0" },
  "yamagera": { artist: "Dion Art", license: "CC BY-SA 4.0" },
  "yamasemi": { artist: "Tokumi", license: "Copyrighted free use" },
  "yamashigi": { artist: "Ronald Slabke", license: "CC BY-SA 3.0" },
  "yanbarukuina": { artist: "(c) Wich’yanan L, some rights reserved (CC BY)", license: "CC BY 4.0" },
  "yatsugashira": { artist: "Gunjan Pandey", license: "CC BY-SA 4.0" },
  "yoshigamo": { artist: "Francis C. Franklin", license: "CC BY-SA 4.0" },
  "yoshigoi": { artist: "JJ Harrison (https://tiny.jjharrison.com.au/t/N...", license: "CC BY-SA 4.0" },
  "yotaka": { artist: "Koshy Koshy", license: "CC BY 2.0" },
  "yukihoojiro": { artist: "Drew Avery", license: "CC BY 2.0" },
  "yurikamome": { artist: "Hans Hillewaert", license: "CC BY-SA 3.0" },
  "zuakaaobato": { artist: "Koolah (talk)", license: "CC BY-SA 3.0" },
  "zugurokamome": { artist: "Kim, Hyun-tae", license: "CC BY 4.0" },
  "zuguromizogoi": { artist: "Francesco Veronesi from Italy", license: "CC BY-SA 2.0" },
};
