const BIRD_DATA = [
  { id: "suzume", name: "スズメ", category: "鳥", image: "images/suzume.jpg", tags: [] },
  { id: "hashibutogarasu", name: "ハシブトガラス", category: "鳥", image: "images/hashibutogarasu.jpg", tags: [] },
  { id: "hashibosogarasu", name: "ハシボソガラス", category: "鳥", image: "images/hashibosogarasu.jpg", tags: [] },
  { id: "kijibato", name: "キジバト", category: "鳥", image: "images/kijibato.jpg", tags: [] },
  { id: "hiyodori", name: "ヒヨドリ", category: "鳥", image: "images/hiyodori.jpg", tags: [] },
  { id: "mejiro", name: "メジロ", category: "鳥", image: "images/mejiro.jpg", tags: [] },
  { id: "shijuukara", name: "シジュウカラ", category: "鳥", image: "images/shijuukara.jpg", tags: [] },
  { id: "tsubame", name: "ツバメ", category: "鳥", image: "images/tsubame.jpg", tags: [] },
  { id: "mukudori", name: "ムクドリ", category: "鳥", image: "images/mukudori.jpg", tags: [] },
  { id: "hakusekirei", name: "ハクセキレイ", category: "鳥", image: "images/hakusekirei.jpg", tags: [] },
  { id: "karugamo", name: "カルガモ", category: "鳥", image: "images/karugamo.jpg", tags: [] },
  { id: "kosagi", name: "コサギ", category: "鳥", image: "images/kosagi.jpg", tags: [] },
  { id: "aosagi", name: "アオサギ", category: "鳥", image: "images/aosagi.jpg", tags: [] },
  { id: "tobi", name: "トビ", category: "鳥", image: "images/tobi.jpg", tags: [] },
  { id: "mozu", name: "モズ", category: "鳥", image: "images/mozu.jpg", tags: [] },
  { id: "uguisu", name: "ウグイス", category: "鳥", image: "images/uguisu.jpg", tags: [] },
  { id: "kawasemi", name: "カワセミ", category: "鳥", image: "images/kawasemi.jpg", tags: [] },
  { id: "joubitaki", name: "ジョウビタキ", category: "鳥", image: "images/joubitaki.jpg", tags: [] },
  { id: "enaga", name: "エナガ", category: "鳥", image: "images/enaga.jpg", tags: [] },
  { id: "kawarahiwa", name: "カワラヒワ", category: "鳥", image: "images/kawarahiwa.jpg", tags: [] },
];
