const BIRD_DATA = [
  { id: "suzume", name: "スズメ", category: "鳥", image: "images/suzume.jpg", tags: [] },
  { id: "hashibutogarasu", name: "ハシブトガラス", category: "鳥", image: "images/hashibutogarasu.jpg", tags: [] },
  { id: "hashibosogarasu", name: "ハシボソガラス", category: "鳥", image: "images/hashibosogarasu.jpg", tags: [] },
  { id: "kijibato", name: "キジバト", category: "鳥", image: "images/kijibato.jpg", tags: [] },
  { id: "hiyodori", name: "ヒヨドリ", category: "鳥", image: "images/hiyodori.jpg", tags: [] },
  { id: "mejiro", name: "メジロ", category: "鳥", image: "images/mejiro.jpg", tags: [] },
  { id: "shijuukara", name: "シジュウカラ", category: "鳥", image: "images/shijuukara.jpg", tags: [] },
  { id: "tsubame", name: "ツバメ", category: "鳥", image: "images/tsubame.jpg", tags: [] },
  { id: "mukudori", name: "ムクドリ", category: "鳥", image: "images/mukudori.jpg", tags: [] },
  { id: "hakusekirei", name: "ハクセキレイ", category: "鳥", image: "images/hakusekirei.jpg", tags: [] },
  { id: "karugamo", name: "カルガモ", category: "鳥", image: "images/karugamo.jpg", tags: [] },
  { id: "kosagi", name: "コサギ", category: "鳥", image: "images/kosagi.jpg", tags: [] },
  { id: "aosagi", name: "アオサギ", category: "鳥", image: "images/aosagi.jpg", tags: [] },
  { id: "tobi", name: "トビ", category: "鳥", image: "images/tobi.jpg", tags: [] },
  { id: "mozu", name: "モズ", category: "鳥", image: "images/mozu.jpg", tags: [] },
  { id: "uguisu", name: "ウグイス", category: "鳥", image: "images/uguisu.jpg", tags: [] },
  { id: "kawasemi", name: "カワセミ", category: "鳥", image: "images/kawasemi.jpg", tags: [] },
  { id: "joubitaki", name: "ジョウビタキ", category: "鳥", image: "images/joubitaki.jpg", tags: [] },
  { id: "enaga", name: "エナガ", category: "鳥", image: "images/enaga.jpg", tags: [] },
  { id: "kawarahiwa", name: "カワラヒワ", category: "鳥", image: "images/kawarahiwa.jpg", tags: [] },
  { id: "ootaka", name: "オオタカ", category: "鳥", image: "images/ootaka.jpg", tags: ["タカ類"] },
  { id: "haitaka", name: "ハイタカ", category: "鳥", image: "images/haitaka.jpg", tags: ["タカ類"] },
  { id: "tsumi", name: "ツミ", category: "鳥", image: "images/tsumi.jpg", tags: ["タカ類"] },
  { id: "nosuri", name: "ノスリ", category: "鳥", image: "images/nosuri.jpg", tags: ["タカ類"] },
  { id: "kumataka", name: "クマタカ", category: "鳥", image: "images/kumataka.jpg", tags: ["タカ類"] },
  { id: "sashiba", name: "サシバ", category: "鳥", image: "images/sashiba.jpg", tags: ["タカ類"] },
  { id: "hachikuma", name: "ハチクマ", category: "鳥", image: "images/hachikuma.jpg", tags: ["タカ類"] },
  { id: "ohwashi", name: "オオワシ", category: "鳥", image: "images/ohwashi.jpg", tags: ["タカ類"] },
  { id: "ojirowanshi", name: "オジロワシ", category: "鳥", image: "images/ojirowanshi.jpg", tags: ["タカ類"] },
  { id: "hayabusa", name: "ハヤブサ", category: "鳥", image: "images/hayabusa.jpg", tags: ["タカ類"] },
  // --- 追加100種以上 (2026-03-30) ---
  // キジ目
  { id: "raichou", name: "ライチョウ", category: "鳥", image: "images/raichou.jpg", tags: ["キジ目"] },
  { id: "kojukei", name: "コジュケイ", category: "鳥", image: "images/kojukei.jpg", tags: ["キジ目"] },
  { id: "yamadori", name: "ヤマドリ", category: "鳥", image: "images/yamadori.jpg", tags: ["キジ目"] },
  { id: "kiji", name: "キジ", category: "鳥", image: "images/kiji.jpg", tags: ["キジ目"] },
  // カモ目
  { id: "magan", name: "マガン", category: "鳥", image: "images/magan.jpg", tags: ["カモ目"] },
  { id: "kobuhakuchou", name: "コブハクチョウ", category: "鳥", image: "images/kobuhakuchou.jpg", tags: ["カモ目"] },
  { id: "oohakuchou", name: "オオハクチョウ", category: "鳥", image: "images/oohakuchou.jpg", tags: ["カモ目"] },
  { id: "oshidori", name: "オシドリ", category: "鳥", image: "images/oshidori.jpg", tags: ["カモ目"] },
  { id: "hidorigamo", name: "ヒドリガモ", category: "鳥", image: "images/hidorigamo.jpg", tags: ["カモ目"] },
  { id: "magamo", name: "マガモ", category: "鳥", image: "images/magamo.jpg", tags: ["カモ目"] },
  { id: "hashibirogamo", name: "ハシビロガモ", category: "鳥", image: "images/hashibirogamo.jpg", tags: ["カモ目"] },
  { id: "onagagamo", name: "オナガガモ", category: "鳥", image: "images/onagagamo.jpg", tags: ["カモ目"] },
  { id: "kogamo", name: "コガモ", category: "鳥", image: "images/kogamo.jpg", tags: ["カモ目"] },
  { id: "hoshihajiro", name: "ホシハジロ", category: "鳥", image: "images/hoshihajiro.jpg", tags: ["カモ目"] },
  { id: "kinkurohajiro", name: "キンクロハジロ", category: "鳥", image: "images/kinkurohajiro.jpg", tags: ["カモ目"] },
  { id: "mikoaisa", name: "ミコアイサ", category: "鳥", image: "images/mikoaisa.jpg", tags: ["カモ目"] },
  // カイツブリ目
  { id: "kaitsuburi", name: "カイツブリ", category: "鳥", image: "images/kaitsuburi.jpg", tags: ["カイツブリ目"] },
  { id: "kanmurikaitsuburi", name: "カンムリカイツブリ", category: "鳥", image: "images/kanmurikaitsuburi.jpg", tags: ["カイツブリ目"] },
  // ハト目
  { id: "kawarabato", name: "カワラバト", category: "鳥", image: "images/kawarabato.jpg", tags: ["ハト目"] },
  { id: "aobato", name: "アオバト", category: "鳥", image: "images/aobato.jpg", tags: ["ハト目"] },
  // コウノトリ目
  { id: "kounotori", name: "コウノトリ", category: "鳥", image: "images/kounotori.jpg", tags: ["コウノトリ目"] },
  // ペリカン目（サギ科）
  { id: "goisagi", name: "ゴイサギ", category: "鳥", image: "images/goisagi.jpg", tags: ["サギ科"] },
  { id: "sasagoi", name: "ササゴイ", category: "鳥", image: "images/sasagoi.jpg", tags: ["サギ科"] },
  { id: "amasagi", name: "アマサギ", category: "鳥", image: "images/amasagi.jpg", tags: ["サギ科"] },
  { id: "daisagi", name: "ダイサギ", category: "鳥", image: "images/daisagi.jpg", tags: ["サギ科"] },
  { id: "chuusagi", name: "チュウサギ", category: "鳥", image: "images/chuusagi.jpg", tags: ["サギ科"] },
  // トキ科
  { id: "toki", name: "トキ", category: "鳥", image: "images/toki.jpg", tags: ["トキ科"] },
  // ツル目
  { id: "tanchou", name: "タンチョウ", category: "鳥", image: "images/tanchou.jpg", tags: ["ツル目"] },
  { id: "nabeduru", name: "ナベヅル", category: "鳥", image: "images/nabeduru.jpg", tags: ["ツル目"] },
  { id: "ban", name: "バン", category: "鳥", image: "images/ban.jpg", tags: ["ツル目"] },
  { id: "ooban", name: "オオバン", category: "鳥", image: "images/ooban.jpg", tags: ["ツル目"] },
  // カッコウ目
  { id: "kakkou", name: "カッコウ", category: "鳥", image: "images/kakkou.jpg", tags: ["カッコウ目"] },
  { id: "hototogisu", name: "ホトトギス", category: "鳥", image: "images/hototogisu.jpg", tags: ["カッコウ目"] },
  { id: "tsutsudori", name: "ツツドリ", category: "鳥", image: "images/tsutsudori.jpg", tags: ["カッコウ目"] },
  // チドリ目
  { id: "tageri", name: "タゲリ", category: "鳥", image: "images/tageri.jpg", tags: ["チドリ目"] },
  { id: "keri", name: "ケリ", category: "鳥", image: "images/keri.jpg", tags: ["チドリ目"] },
  { id: "kochidori", name: "コチドリ", category: "鳥", image: "images/kochidori.jpg", tags: ["チドリ目"] },
  { id: "isoshigi", name: "イソシギ", category: "鳥", image: "images/isoshigi.jpg", tags: ["チドリ目"] },
  { id: "yurikamome", name: "ユリカモメ", category: "鳥", image: "images/yurikamome.jpg", tags: ["チドリ目"] },
  { id: "umineko", name: "ウミネコ", category: "鳥", image: "images/umineko.jpg", tags: ["チドリ目"] },
  { id: "segurokamome", name: "セグロカモメ", category: "鳥", image: "images/segurokamome.jpg", tags: ["チドリ目"] },
  // タカ目（追加分）
  { id: "misago", name: "ミサゴ", category: "鳥", image: "images/misago.jpg", tags: ["タカ類"] },
  { id: "chuuhi", name: "チュウヒ", category: "鳥", image: "images/chuuhi.jpg", tags: ["タカ類"] },
  { id: "inuwashi", name: "イヌワシ", category: "鳥", image: "images/inuwashi.jpg", tags: ["タカ類"] },
  { id: "kanmuriwashi", name: "カンムリワシ", category: "鳥", image: "images/kanmuriwashi.jpg", tags: ["タカ類"] },
  // フクロウ目
  { id: "fukurou", name: "フクロウ", category: "鳥", image: "images/fukurou.jpg", tags: ["フクロウ目"] },
  { id: "aobazuku", name: "アオバズク", category: "鳥", image: "images/aobazuku.jpg", tags: ["フクロウ目"] },
  { id: "konohazuku", name: "コノハズク", category: "鳥", image: "images/konohazuku.jpg", tags: ["フクロウ目"] },
  { id: "komimizuku", name: "コミミズク", category: "鳥", image: "images/komimizuku.jpg", tags: ["フクロウ目"] },
  { id: "shimafukurou", name: "シマフクロウ", category: "鳥", image: "images/shimafukurou.jpg", tags: ["フクロウ目"] },
  // ブッポウソウ目・カワセミ科
  { id: "akashoubin", name: "アカショウビン", category: "鳥", image: "images/akashoubin.jpg", tags: ["カワセミ科"] },
  { id: "yamasemi", name: "ヤマセミ", category: "鳥", image: "images/yamasemi.jpg", tags: ["カワセミ科"] },
  { id: "buppousou", name: "ブッポウソウ", category: "鳥", image: "images/buppousou.jpg", tags: ["ブッポウソウ目"] },
  // キツツキ目
  { id: "kogera", name: "コゲラ", category: "鳥", image: "images/kogera.jpg", tags: ["キツツキ目"] },
  { id: "akagera", name: "アカゲラ", category: "鳥", image: "images/akagera.jpg", tags: ["キツツキ目"] },
  { id: "aogera", name: "アオゲラ", category: "鳥", image: "images/aogera.jpg", tags: ["キツツキ目"] },
  { id: "kumagera", name: "クマゲラ", category: "鳥", image: "images/kumagera.jpg", tags: ["キツツキ目"] },
  { id: "arisui", name: "アリスイ", category: "鳥", image: "images/arisui.jpg", tags: ["キツツキ目"] },
  // ハヤブサ目
  { id: "chougenbou", name: "チョウゲンボウ", category: "鳥", image: "images/chougenbou.jpg", tags: ["タカ類"] },
  // スズメ目 — カラス科・モズ科
  { id: "sankouchou", name: "サンコウチョウ", category: "鳥", image: "images/sankouchou.jpg", tags: ["スズメ目"] },
  { id: "kakesu", name: "カケス", category: "鳥", image: "images/kakesu.jpg", tags: ["カラス科"] },
  { id: "onaga", name: "オナガ", category: "鳥", image: "images/onaga.jpg", tags: ["カラス科"] },
  { id: "kasasagi", name: "カササギ", category: "鳥", image: "images/kasasagi.jpg", tags: ["カラス科"] },
  { id: "hoshigarasu", name: "ホシガラス", category: "鳥", image: "images/hoshigarasu.jpg", tags: ["カラス科"] },
  // シジュウカラ科
  { id: "kikuitadaki", name: "キクイタダキ", category: "鳥", image: "images/kikuitadaki.jpg", tags: ["スズメ目"] },
  { id: "kogara", name: "コガラ", category: "鳥", image: "images/kogara.jpg", tags: ["シジュウカラ科"] },
  { id: "higara", name: "ヒガラ", category: "鳥", image: "images/higara.jpg", tags: ["シジュウカラ科"] },
  { id: "yamagara", name: "ヤマガラ", category: "鳥", image: "images/yamagara.jpg", tags: ["シジュウカラ科"] },
  // ヒバリ科・ツバメ科
  { id: "hibari", name: "ヒバリ", category: "鳥", image: "images/hibari.jpg", tags: ["スズメ目"] },
  { id: "koshiakatsubame", name: "コシアカツバメ", category: "鳥", image: "images/koshiakatsubame.jpg", tags: ["ツバメ科"] },
  { id: "iwatsubame", name: "イワツバメ", category: "鳥", image: "images/iwatsubame.jpg", tags: ["ツバメ科"] },
  // ウグイス科・ムシクイ科
  { id: "yabusame", name: "ヤブサメ", category: "鳥", image: "images/yabusame.jpg", tags: ["スズメ目"] },
  { id: "sendaimushikui", name: "センダイムシクイ", category: "鳥", image: "images/sendaimushikui.jpg", tags: ["スズメ目"] },
  // チメドリ科・外来種
  { id: "gabichou", name: "ガビチョウ", category: "鳥", image: "images/gabichou.jpg", tags: ["外来種"] },
  { id: "soushichou", name: "ソウシチョウ", category: "鳥", image: "images/soushichou.jpg", tags: ["外来種"] },
  // ヨシキリ科・セッカ科
  { id: "ooyoshikiri", name: "オオヨシキリ", category: "鳥", image: "images/ooyoshikiri.jpg", tags: ["スズメ目"] },
  { id: "sekka", name: "セッカ", category: "鳥", image: "images/sekka.jpg", tags: ["スズメ目"] },
  // レンジャク科
  { id: "kirenjaku", name: "キレンジャク", category: "鳥", image: "images/kirenjaku.jpg", tags: ["スズメ目"] },
  { id: "hirenjaku", name: "ヒレンジャク", category: "鳥", image: "images/hirenjaku.jpg", tags: ["スズメ目"] },
  // ゴジュウカラ科・ミソサザイ科
  { id: "gojuukara", name: "ゴジュウカラ", category: "鳥", image: "images/gojuukara.jpg", tags: ["スズメ目"] },
  { id: "misosazai", name: "ミソサザイ", category: "鳥", image: "images/misosazai.jpg", tags: ["スズメ目"] },
  // ムクドリ科
  { id: "komukudori", name: "コムクドリ", category: "鳥", image: "images/komukudori.jpg", tags: ["スズメ目"] },
  // カワガラス科
  { id: "kawagarasu", name: "カワガラス", category: "鳥", image: "images/kawagarasu.jpg", tags: ["スズメ目"] },
  // ヒタキ科（ツグミ類）
  { id: "toratsugumi", name: "トラツグミ", category: "鳥", image: "images/toratsugumi.jpg", tags: ["ヒタキ科"] },
  { id: "kurotsugumi", name: "クロツグミ", category: "鳥", image: "images/kurotsugumi.jpg", tags: ["ヒタキ科"] },
  { id: "shirohara", name: "シロハラ", category: "鳥", image: "images/shirohara.jpg", tags: ["ヒタキ科"] },
  { id: "akahara", name: "アカハラ", category: "鳥", image: "images/akahara.jpg", tags: ["ヒタキ科"] },
  { id: "komadori", name: "コマドリ", category: "鳥", image: "images/komadori.jpg", tags: ["ヒタキ科"] },
  { id: "ruribitaki", name: "ルリビタキ", category: "鳥", image: "images/ruribitaki.jpg", tags: ["ヒタキ科"] },
  { id: "nobitaki", name: "ノビタキ", category: "鳥", image: "images/nobitaki.jpg", tags: ["ヒタキ科"] },
  { id: "isohiyodori", name: "イソヒヨドリ", category: "鳥", image: "images/isohiyodori.jpg", tags: ["ヒタキ科"] },
  { id: "kibitaki", name: "キビタキ", category: "鳥", image: "images/kibitaki.jpg", tags: ["ヒタキ科"] },
  { id: "ooruri", name: "オオルリ", category: "鳥", image: "images/ooruri.jpg", tags: ["ヒタキ科"] },
  // イワヒバリ科
  { id: "iwahibari", name: "イワヒバリ", category: "鳥", image: "images/iwahibari.jpg", tags: ["スズメ目"] },
  // セキレイ科
  { id: "kisekirei", name: "キセキレイ", category: "鳥", image: "images/kisekirei.jpg", tags: ["セキレイ科"] },
  { id: "segurosekirei", name: "セグロセキレイ", category: "鳥", image: "images/segurosekirei.jpg", tags: ["セキレイ科"] },
  { id: "binzui", name: "ビンズイ", category: "鳥", image: "images/binzui.jpg", tags: ["セキレイ科"] },
  // アトリ科
  { id: "atori", name: "アトリ", category: "鳥", image: "images/atori.jpg", tags: ["アトリ科"] },
  { id: "mahiwa", name: "マヒワ", category: "鳥", image: "images/mahiwa.jpg", tags: ["アトリ科"] },
  { id: "benimashiko", name: "ベニマシコ", category: "鳥", image: "images/benimashiko.jpg", tags: ["アトリ科"] },
  { id: "uso", name: "ウソ", category: "鳥", image: "images/uso.jpg", tags: ["アトリ科"] },
  { id: "shime", name: "シメ", category: "鳥", image: "images/shime.jpg", tags: ["アトリ科"] },
  { id: "ikaru", name: "イカル", category: "鳥", image: "images/ikaru.jpg", tags: ["アトリ科"] },
  // ホオジロ科
  { id: "hoojiro", name: "ホオジロ", category: "鳥", image: "images/hoojiro.jpg", tags: ["ホオジロ科"] },
  { id: "kashiradaka", name: "カシラダカ", category: "鳥", image: "images/kashiradaka.jpg", tags: ["ホオジロ科"] },
  { id: "aoji", name: "アオジ", category: "鳥", image: "images/aoji.jpg", tags: ["ホオジロ科"] },
  { id: "oojurin", name: "オオジュリン", category: "鳥", image: "images/oojurin.jpg", tags: ["ホオジロ科"] },
  // --- 追加100種 第2弾 (2026-03-30) ---
  // キジ目（残り）
  { id: "ezoraichou", name: "エゾライチョウ", category: "鳥", image: "images/ezoraichou.jpg", tags: ["キジ目"] },
  { id: "uzura", name: "ウズラ", category: "鳥", image: "images/uzura.jpg", tags: ["キジ目"] },
  { id: "tairikukiji", name: "タイリクキジ", category: "鳥", image: "images/tairikukiji.jpg", tags: ["キジ目"] },
  // カモ目（残り）
  { id: "hishikui", name: "ヒシクイ", category: "鳥", image: "images/hishikui.jpg", tags: ["カモ目"] },
  { id: "karigane", name: "カリガネ", category: "鳥", image: "images/karigane.jpg", tags: ["カモ目"] },
  { id: "hakugan", name: "ハクガン", category: "鳥", image: "images/hakugan.jpg", tags: ["カモ目"] },
  { id: "shijuukaragaN", name: "シジュウカラガン", category: "鳥", image: "images/shijuukaragaN.jpg", tags: ["カモ目"] },
  { id: "kokugan", name: "コクガン", category: "鳥", image: "images/kokugan.jpg", tags: ["カモ目"] },
  { id: "kohakuchou", name: "コハクチョウ", category: "鳥", image: "images/kohakuchou.jpg", tags: ["カモ目"] },
  { id: "tsukushigamo", name: "ツクシガモ", category: "鳥", image: "images/tsukushigamo.jpg", tags: ["カモ目"] },
  { id: "okayoshigamo", name: "オカヨシガモ", category: "鳥", image: "images/okayoshigamo.jpg", tags: ["カモ目"] },
  { id: "yoshigamo", name: "ヨシガモ", category: "鳥", image: "images/yoshigamo.jpg", tags: ["カモ目"] },
  { id: "amerikahidori", name: "アメリカヒドリ", category: "鳥", image: "images/amerikahidori.jpg", tags: ["カモ目"] },
  { id: "shimaaji", name: "シマアジ", category: "鳥", image: "images/shimaaji.jpg", tags: ["カモ目"] },
  { id: "tomoegamo", name: "トモエガモ", category: "鳥", image: "images/tomoegamo.jpg", tags: ["カモ目"] },
  { id: "suzugamo", name: "スズガモ", category: "鳥", image: "images/suzugamo.jpg", tags: ["カモ目"] },
  { id: "shinorigamo", name: "シノリガモ", category: "鳥", image: "images/shinorigamo.jpg", tags: ["カモ目"] },
  { id: "kurogamo", name: "クロガモ", category: "鳥", image: "images/kurogamo.jpg", tags: ["カモ目"] },
  { id: "koorigamo", name: "コオリガモ", category: "鳥", image: "images/koorigamo.jpg", tags: ["カモ目"] },
  { id: "hoojirogamo", name: "ホオジロガモ", category: "鳥", image: "images/hoojirogamo.jpg", tags: ["カモ目"] },
  { id: "kawaaisa", name: "カワアイサ", category: "鳥", image: "images/kawaaisa.jpg", tags: ["カモ目"] },
  { id: "umiaisa", name: "ウミアイサ", category: "鳥", image: "images/umiaisa.jpg", tags: ["カモ目"] },
  // カイツブリ目（残り）
  { id: "akaerikaitsuburi", name: "アカエリカイツブリ", category: "鳥", image: "images/akaerikaitsuburi.jpg", tags: ["カイツブリ目"] },
  { id: "mimikaitsuburi", name: "ミミカイツブリ", category: "鳥", image: "images/mimikaitsuburi.jpg", tags: ["カイツブリ目"] },
  { id: "hajirokaitsuburi", name: "ハジロカイツブリ", category: "鳥", image: "images/hajirokaitsuburi.jpg", tags: ["カイツブリ目"] },
  // ハト目（残り）
  { id: "karasubato", name: "カラスバト", category: "鳥", image: "images/karasubato.jpg", tags: ["ハト目"] },
  { id: "shirakobato", name: "シラコバト", category: "鳥", image: "images/shirakobato.jpg", tags: ["ハト目"] },
  { id: "kinbato", name: "キンバト", category: "鳥", image: "images/kinbato.jpg", tags: ["ハト目"] },
  { id: "zuakaaobato", name: "ズアカアオバト", category: "鳥", image: "images/zuakaaobato.jpg", tags: ["ハト目"] },
  // アビ目
  { id: "abi", name: "アビ", category: "鳥", image: "images/abi.jpg", tags: ["アビ目"] },
  { id: "oohamu", name: "オオハム", category: "鳥", image: "images/oohamu.jpg", tags: ["アビ目"] },
  { id: "shiroerioohamu", name: "シロエリオオハム", category: "鳥", image: "images/shiroerioohamu.jpg", tags: ["アビ目"] },
  // ミズナギドリ目
  { id: "ahoudori", name: "アホウドリ", category: "鳥", image: "images/ahoudori.jpg", tags: ["ミズナギドリ目"] },
  { id: "koahoudori", name: "コアホウドリ", category: "鳥", image: "images/koahoudori.jpg", tags: ["ミズナギドリ目"] },
  { id: "kuroashiahoudori", name: "クロアシアホウドリ", category: "鳥", image: "images/kuroashiahoudori.jpg", tags: ["ミズナギドリ目"] },
  { id: "oomizunagidori", name: "オオミズナギドリ", category: "鳥", image: "images/oomizunagidori.jpg", tags: ["ミズナギドリ目"] },
  // カツオドリ目・ウ科
  { id: "katsuodori", name: "カツオドリ", category: "鳥", image: "images/katsuodori.jpg", tags: ["カツオドリ目"] },
  { id: "himeu", name: "ヒメウ", category: "鳥", image: "images/himeu.jpg", tags: ["ウ科"] },
  { id: "kawau", name: "カワウ", category: "鳥", image: "images/kawau.jpg", tags: ["ウ科"] },
  { id: "umiu", name: "ウミウ", category: "鳥", image: "images/umiu.jpg", tags: ["ウ科"] },
  // ペリカン目（残り）
  { id: "murasakisagi", name: "ムラサキサギ", category: "鳥", image: "images/murasakisagi.jpg", tags: ["サギ科"] },
  { id: "kurosagi", name: "クロサギ", category: "鳥", image: "images/kurosagi.jpg", tags: ["サギ科"] },
  { id: "herasagi", name: "ヘラサギ", category: "鳥", image: "images/herasagi.jpg", tags: ["トキ科"] },
  { id: "kurotsuraherasagi", name: "クロツラヘラサギ", category: "鳥", image: "images/kurotsuraherasagi.jpg", tags: ["トキ科"] },
  // ツル目（残り）
  { id: "kanadaduru", name: "カナダヅル", category: "鳥", image: "images/kanadaduru.jpg", tags: ["ツル目"] },
  { id: "manaduru", name: "マナヅル", category: "鳥", image: "images/manaduru.jpg", tags: ["ツル目"] },
  { id: "kuroduru", name: "クロヅル", category: "鳥", image: "images/kuroduru.jpg", tags: ["ツル目"] },
  { id: "yanbarukuina", name: "ヤンバルクイナ", category: "鳥", image: "images/yanbarukuina.jpg", tags: ["ツル目"] },
  { id: "kuina", name: "クイナ", category: "鳥", image: "images/kuina.jpg", tags: ["ツル目"] },
  { id: "hikuina", name: "ヒクイナ", category: "鳥", image: "images/hikuina.jpg", tags: ["ツル目"] },
  // カッコウ目（残り）
  { id: "juuichi", name: "ジュウイチ", category: "鳥", image: "images/juuichi.jpg", tags: ["カッコウ目"] },
  // ヨタカ目
  { id: "yotaka", name: "ヨタカ", category: "鳥", image: "images/yotaka.jpg", tags: ["ヨタカ目"] },
  // アマツバメ目
  { id: "amatsubame", name: "アマツバメ", category: "鳥", image: "images/amatsubame.jpg", tags: ["アマツバメ目"] },
  // チドリ目（残りシギ・チドリ類）
  { id: "munaguro", name: "ムナグロ", category: "鳥", image: "images/munaguro.jpg", tags: ["チドリ目"] },
  { id: "daizen", name: "ダイゼン", category: "鳥", image: "images/daizen.jpg", tags: ["チドリ目"] },
  { id: "ikaruchidori", name: "イカルチドリ", category: "鳥", image: "images/ikaruchidori.jpg", tags: ["チドリ目"] },
  { id: "shirochidori", name: "シロチドリ", category: "鳥", image: "images/shirochidori.jpg", tags: ["チドリ目"] },
  { id: "medaichidori", name: "メダイチドリ", category: "鳥", image: "images/medaichidori.jpg", tags: ["チドリ目"] },
  { id: "miyakodori", name: "ミヤコドリ", category: "鳥", image: "images/miyakodori.jpg", tags: ["チドリ目"] },
  { id: "seitakashigi", name: "セイタカシギ", category: "鳥", image: "images/seitakashigi.jpg", tags: ["チドリ目"] },
  { id: "yamashigi", name: "ヤマシギ", category: "鳥", image: "images/yamashigi.jpg", tags: ["シギ科"] },
  { id: "oojishigi", name: "オオジシギ", category: "鳥", image: "images/oojishigi.jpg", tags: ["シギ科"] },
  { id: "tashigi", name: "タシギ", category: "鳥", image: "images/tashigi.jpg", tags: ["シギ科"] },
  { id: "oguroshigi", name: "オグロシギ", category: "鳥", image: "images/oguroshigi.jpg", tags: ["シギ科"] },
  { id: "oosorihashishigi", name: "オオソリハシシギ", category: "鳥", image: "images/oosorihashishigi.jpg", tags: ["シギ科"] },
  { id: "chuushakushigi", name: "チュウシャクシギ", category: "鳥", image: "images/chuushakushigi.jpg", tags: ["シギ科"] },
  { id: "hourokushigi", name: "ホウロクシギ", category: "鳥", image: "images/hourokushigi.jpg", tags: ["シギ科"] },
  { id: "aoashishigi", name: "アオアシシギ", category: "鳥", image: "images/aoashishigi.jpg", tags: ["シギ科"] },
  { id: "kiashishigi", name: "キアシシギ", category: "鳥", image: "images/kiashishigi.jpg", tags: ["シギ科"] },
  { id: "kyoujoshigi", name: "キョウジョシギ", category: "鳥", image: "images/kyoujoshigi.jpg", tags: ["シギ科"] },
  { id: "tounen", name: "トウネン", category: "鳥", image: "images/tounen.jpg", tags: ["シギ科"] },
  { id: "hamashigi", name: "ハマシギ", category: "鳥", image: "images/hamashigi.jpg", tags: ["シギ科"] },
  { id: "koajisashi", name: "コアジサシ", category: "鳥", image: "images/koajisashi.jpg", tags: ["カモメ科"] },
  { id: "ajisashi", name: "アジサシ", category: "鳥", image: "images/ajisashi.jpg", tags: ["カモメ科"] },
  { id: "oosegurokamome", name: "オオセグロカモメ", category: "鳥", image: "images/oosegurokamome.jpg", tags: ["カモメ科"] },
  // タカ目（残り）
  { id: "haiirochUhi", name: "ハイイロチュウヒ", category: "鳥", image: "images/haiirochUhi.jpg", tags: ["タカ類"] },
  { id: "keashinosuri", name: "ケアシノスリ", category: "鳥", image: "images/keashinosuri.jpg", tags: ["タカ類"] },
  // フクロウ目（残り）
  { id: "ookonohazuku", name: "オオコノハズク", category: "鳥", image: "images/ookonohazuku.jpg", tags: ["フクロウ目"] },
  { id: "torafuzuku", name: "トラフズク", category: "鳥", image: "images/torafuzuku.jpg", tags: ["フクロウ目"] },
  // サイチョウ目
  { id: "yatsugashira", name: "ヤツガシラ", category: "鳥", image: "images/yatsugashira.jpg", tags: ["サイチョウ目"] },
  // キツツキ目（残り）
  { id: "ooakagera", name: "オオアカゲラ", category: "鳥", image: "images/ooakagera.jpg", tags: ["キツツキ目"] },
  { id: "yamagera", name: "ヤマゲラ", category: "鳥", image: "images/yamagera.jpg", tags: ["キツツキ目"] },
  { id: "noguchigera", name: "ノグチゲラ", category: "鳥", image: "images/noguchigera.jpg", tags: ["キツツキ目"] },
  // ハヤブサ目（残り）
  { id: "chigohayabusa", name: "チゴハヤブサ", category: "鳥", image: "images/chigohayabusa.jpg", tags: ["タカ類"] },
  // スズメ目（残り）
  { id: "sanshokui", name: "サンショウクイ", category: "鳥", image: "images/sanshokui.jpg", tags: ["スズメ目"] },
  { id: "chigomozu", name: "チゴモズ", category: "鳥", image: "images/chigomozu.jpg", tags: ["モズ科"] },
  { id: "akamozu", name: "アカモズ", category: "鳥", image: "images/akamozu.jpg", tags: ["モズ科"] },
  { id: "oomozu", name: "オオモズ", category: "鳥", image: "images/oomozu.jpg", tags: ["モズ科"] },
  { id: "rurikakesu", name: "ルリカケス", category: "鳥", image: "images/rurikakesu.jpg", tags: ["カラス科"] },
  { id: "kokumarugarasu", name: "コクマルガラス", category: "鳥", image: "images/kokumarugarasu.jpg", tags: ["カラス科"] },
  { id: "miyamagarasu", name: "ミヤマガラス", category: "鳥", image: "images/miyamagarasu.jpg", tags: ["カラス科"] },
  { id: "watarigarasu", name: "ワタリガラス", category: "鳥", image: "images/watarigarasu.jpg", tags: ["カラス科"] },
  { id: "hashibutogara", name: "ハシブトガラ", category: "鳥", image: "images/hashibutogara.jpg", tags: ["シジュウカラ科"] },
  { id: "shoudoutsubame", name: "ショウドウツバメ", category: "鳥", image: "images/shoudoutsubame.jpg", tags: ["ツバメ科"] },
  { id: "shirogashira", name: "シロガシラ", category: "鳥", image: "images/shirogashira.jpg", tags: ["スズメ目"] },
  { id: "meguro", name: "メグロ", category: "鳥", image: "images/meguro.jpg", tags: ["スズメ目"] },
  { id: "oosekka", name: "オオセッカ", category: "鳥", image: "images/oosekka.jpg", tags: ["スズメ目"] },
  { id: "hakkachou", name: "ハッカチョウ", category: "鳥", image: "images/hakkachou.jpg", tags: ["外来種"] },
  { id: "ginmukudori", name: "ギンムクドリ", category: "鳥", image: "images/ginmukudori.jpg", tags: ["スズメ目"] },
  { id: "hoshimukudori", name: "ホシムクドリ", category: "鳥", image: "images/hoshimukudori.jpg", tags: ["スズメ目"] },
  // --- 追加 第3弾 (2026-03-30) 残り全種 ---
  // サギ科（サンカノゴイ・ヨシゴイ類）
  { id: "sankanogoi", name: "サンカノゴイ", category: "鳥", image: "images/sankanogoi.jpg", tags: ["サギ科"] },
  { id: "yoshigoi", name: "ヨシゴイ", category: "鳥", image: "images/yoshigoi.jpg", tags: ["サギ科"] },
  { id: "ooyoshigoi", name: "オオヨシゴイ", category: "鳥", image: "images/ooyoshigoi.jpg", tags: ["サギ科"] },
  { id: "ryuukyuuyoshigoi", name: "リュウキュウヨシゴイ", category: "鳥", image: "images/ryuukyuuyoshigoi.jpg", tags: ["サギ科"] },
  { id: "mizogoi", name: "ミゾゴイ", category: "鳥", image: "images/mizogoi.jpg", tags: ["サギ科"] },
  { id: "zuguromizogoi", name: "ズグロミゾゴイ", category: "鳥", image: "images/zuguromizogoi.jpg", tags: ["サギ科"] },
  { id: "akagashirasagi", name: "アカガシラサギ", category: "鳥", image: "images/akagashirasagi.jpg", tags: ["サギ科"] },
  // ツル目（残り）
  { id: "shiroharakuina", name: "シロハラクイナ", category: "鳥", image: "images/shiroharakuina.jpg", tags: ["ツル目"] },
  // カッコウ目（残り）
  { id: "segurokakkou", name: "セグロカッコウ", category: "鳥", image: "images/segurokakkou.jpg", tags: ["カッコウ目"] },
  // アマツバメ目（残り）
  { id: "harioamatsubame", name: "ハリオアマツバメ", category: "鳥", image: "images/harioamatsubame.jpg", tags: ["アマツバメ目"] },
  { id: "himeamatsubame", name: "ヒメアマツバメ", category: "鳥", image: "images/himeamatsubame.jpg", tags: ["アマツバメ目"] },
  // チドリ目（シギ・カモメ類 残り）
  { id: "sorihashiseitakashigi", name: "ソリハシセイタカシギ", category: "鳥", image: "images/sorihashiseitakashigi.jpg", tags: ["チドリ目"] },
  { id: "amamiyamashigi", name: "アマミヤマシギ", category: "鳥", image: "images/amamiyamashigi.jpg", tags: ["シギ科"] },
  { id: "aoshigi", name: "アオシギ", category: "鳥", image: "images/aoshigi.jpg", tags: ["シギ科"] },
  { id: "oohashishigi", name: "オオハシシギ", category: "鳥", image: "images/oohashishigi.jpg", tags: ["シギ科"] },
  { id: "daishakushigi", name: "ダイシャクシギ", category: "鳥", image: "images/daishakushigi.jpg", tags: ["シギ科"] },
  { id: "tsurushigi", name: "ツルシギ", category: "鳥", image: "images/tsurushigi.jpg", tags: ["シギ科"] },
  { id: "akaashishigi", name: "アカアシシギ", category: "鳥", image: "images/akaashishigi.jpg", tags: ["シギ科"] },
  { id: "koaoashishigi", name: "コアオアシシギ", category: "鳥", image: "images/koaoashishigi.jpg", tags: ["シギ科"] },
  { id: "kusashigi", name: "クサシギ", category: "鳥", image: "images/kusashigi.jpg", tags: ["シギ科"] },
  { id: "takabushigi", name: "タカブシギ", category: "鳥", image: "images/takabushigi.jpg", tags: ["シギ科"] },
  { id: "sorihashishigi", name: "ソリハシシギ", category: "鳥", image: "images/sorihashishigi.jpg", tags: ["シギ科"] },
  { id: "obashigi", name: "オバシギ", category: "鳥", image: "images/obashigi.jpg", tags: ["シギ科"] },
  { id: "miyubishigi", name: "ミユビシギ", category: "鳥", image: "images/miyubishigi.jpg", tags: ["シギ科"] },
  { id: "ojirotounen", name: "オジロトウネン", category: "鳥", image: "images/ojirotounen.jpg", tags: ["シギ科"] },
  { id: "hibarishigi", name: "ヒバリシギ", category: "鳥", image: "images/hibarishigi.jpg", tags: ["シギ科"] },
  { id: "uzurashigi", name: "ウズラシギ", category: "鳥", image: "images/uzurashigi.jpg", tags: ["シギ科"] },
  { id: "saruhamashigi", name: "サルハマシギ", category: "鳥", image: "images/saruhamashigi.jpg", tags: ["シギ科"] },
  { id: "herashigi", name: "ヘラシギ", category: "鳥", image: "images/herashigi.jpg", tags: ["シギ科"] },
  { id: "erimakishigi", name: "エリマキシギ", category: "鳥", image: "images/erimakishigi.jpg", tags: ["シギ科"] },
  { id: "akaerihireashishigi", name: "アカエリヒレアシシギ", category: "鳥", image: "images/akaerihireashishigi.jpg", tags: ["シギ科"] },
  { id: "renkaku", name: "レンカク", category: "鳥", image: "images/renkaku.jpg", tags: ["チドリ目"] },
  { id: "tamashigi", name: "タマシギ", category: "鳥", image: "images/tamashigi.jpg", tags: ["チドリ目"] },
  { id: "mifuuzura", name: "ミフウズラ", category: "鳥", image: "images/mifuuzura.jpg", tags: ["チドリ目"] },
  { id: "tsubamechidori", name: "ツバメチドリ", category: "鳥", image: "images/tsubamechidori.jpg", tags: ["チドリ目"] },
  { id: "kuroajisashi", name: "クロアジサシ", category: "鳥", image: "images/kuroajisashi.jpg", tags: ["カモメ科"] },
  { id: "mitsuyubikamome", name: "ミツユビカモメ", category: "鳥", image: "images/mitsuyubikamome.jpg", tags: ["カモメ科"] },
  { id: "zugurokamome", name: "ズグロカモメ", category: "鳥", image: "images/zugurokamome.jpg", tags: ["カモメ科"] },
  { id: "kamome", name: "カモメ", category: "鳥", image: "images/kamome.jpg", tags: ["カモメ科"] },
  { id: "washikamome", name: "ワシカモメ", category: "鳥", image: "images/washikamome.jpg", tags: ["カモメ科"] },
  { id: "shirokamome", name: "シロカモメ", category: "鳥", image: "images/shirokamome.jpg", tags: ["カモメ科"] },
  { id: "beniajisashi", name: "ベニアジサシ", category: "鳥", image: "images/beniajisashi.jpg", tags: ["カモメ科"] },
  { id: "eriguroajisashi", name: "エリグロアジサシ", category: "鳥", image: "images/eriguroajisashi.jpg", tags: ["カモメ科"] },
  { id: "touzokukamome", name: "トウゾクカモメ", category: "鳥", image: "images/touzokukamome.jpg", tags: ["チドリ目"] },
  { id: "umigarasu", name: "ウミガラス", category: "鳥", image: "images/umigarasu.jpg", tags: ["ウミスズメ科"] },
  { id: "keimafuri", name: "ケイマフリ", category: "鳥", image: "images/keimafuri.jpg", tags: ["ウミスズメ科"] },
  { id: "umisuzume", name: "ウミスズメ", category: "鳥", image: "images/umisuzume.jpg", tags: ["ウミスズメ科"] },
  { id: "kanmuriUmisuzume", name: "カンムリウミスズメ", category: "鳥", image: "images/kanmuriUmisuzume.jpg", tags: ["ウミスズメ科"] },
  { id: "utou", name: "ウトウ", category: "鳥", image: "images/utou.jpg", tags: ["ウミスズメ科"] },
  { id: "etopirika", name: "エトピリカ", category: "鳥", image: "images/etopirika.jpg", tags: ["ウミスズメ科"] },
  // ウミツバメ科
  { id: "himekuroumitsubame", name: "ヒメクロウミツバメ", category: "鳥", image: "images/himekuroumitsubame.jpg", tags: ["ミズナギドリ目"] },
  // チシマウガラス
  { id: "chishimaugarasu", name: "チシマウガラス", category: "鳥", image: "images/chishimaugarasu.jpg", tags: ["ウ科"] },
  // フクロウ目（残り）
  { id: "ryuukyuukonohazuku", name: "リュウキュウコノハズク", category: "鳥", image: "images/ryuukyuukonohazuku.jpg", tags: ["フクロウ目"] },
  // オウム目
  { id: "honseiinko", name: "ホンセイインコ", category: "鳥", image: "images/honseiinko.jpg", tags: ["外来種"] },
  // スズメ目（残り）
  { id: "yaIrochou", name: "ヤイロチョウ", category: "鳥", image: "images/yaIrochou.jpg", tags: ["スズメ目"] },
  { id: "ryuukyuusanshoukui", name: "リュウキュウサンショウクイ", category: "鳥", image: "images/ryuukyuusanshoukui.jpg", tags: ["スズメ目"] },
  { id: "kouraiuguisu", name: "コウライウグイス", category: "鳥", image: "images/kouraiuguisu.jpg", tags: ["スズメ目"] },
  { id: "ouchuu", name: "オウチュウ", category: "鳥", image: "images/ouchuu.jpg", tags: ["スズメ目"] },
  { id: "oriigara", name: "オリイガラ", category: "鳥", image: "images/oriigara.jpg", tags: ["シジュウカラ科"] },
  { id: "tsurisugara", name: "ツリスガラ", category: "鳥", image: "images/tsurisugara.jpg", tags: ["スズメ目"] },
  // ムシクイ科
  { id: "kimayumushikui", name: "キマユムシクイ", category: "鳥", image: "images/kimayumushikui.jpg", tags: ["スズメ目"] },
  { id: "mebosomushikui", name: "メボソムシクイ", category: "鳥", image: "images/mebosomushikui.jpg", tags: ["スズメ目"] },
  { id: "ezomushikui", name: "エゾムシクイ", category: "鳥", image: "images/ezomushikui.jpg", tags: ["スズメ目"] },
  { id: "iijimamushikui", name: "イイジマムシクイ", category: "鳥", image: "images/iijimamushikui.jpg", tags: ["スズメ目"] },
  // センニュウ科
  { id: "makinosennyu", name: "マキノセンニュウ", category: "鳥", image: "images/makinosennyu.jpg", tags: ["スズメ目"] },
  { id: "shimasennyu", name: "シマセンニュウ", category: "鳥", image: "images/shimasennyu.jpg", tags: ["スズメ目"] },
  { id: "uchiyamasennyu", name: "ウチヤマセンニュウ", category: "鳥", image: "images/uchiyamasennyu.jpg", tags: ["スズメ目"] },
  { id: "ezosennyu", name: "エゾセンニュウ", category: "鳥", image: "images/ezosennyu.jpg", tags: ["スズメ目"] },
  // ヨシキリ科（残り）
  { id: "koyoshikiri", name: "コヨシキリ", category: "鳥", image: "images/koyoshikiri.jpg", tags: ["スズメ目"] },
  // キバシリ科
  { id: "kibashiri", name: "キバシリ", category: "鳥", image: "images/kibashiri.jpg", tags: ["スズメ目"] },
  // ヒタキ科（残り）
  { id: "mamijiro", name: "マミジロ", category: "鳥", image: "images/mamijiro.jpg", tags: ["ヒタキ科"] },
  { id: "minamitoratsugumi", name: "ミナミトラツグミ", category: "鳥", image: "images/minamitoratsugumi.jpg", tags: ["ヒタキ科"] },
  { id: "karaakahara", name: "カラアカハラ", category: "鳥", image: "images/karaakahara.jpg", tags: ["ヒタキ科"] },
  { id: "mamichajinai", name: "マミチャジナイ", category: "鳥", image: "images/mamichajinai.jpg", tags: ["ヒタキ科"] },
  { id: "akahige", name: "アカヒゲ", category: "鳥", image: "images/akahige.jpg", tags: ["ヒタキ科"] },
  { id: "nogoma", name: "ノゴマ", category: "鳥", image: "images/nogoma.jpg", tags: ["ヒタキ科"] },
  { id: "koruri", name: "コルリ", category: "鳥", image: "images/koruri.jpg", tags: ["ヒタキ科"] },
  { id: "shimagoma", name: "シマゴマ", category: "鳥", image: "images/shimagoma.jpg", tags: ["ヒタキ科"] },
  { id: "ezobitaki", name: "エゾビタキ", category: "鳥", image: "images/ezobitaki.jpg", tags: ["ヒタキ科"] },
  { id: "samebitaki", name: "サメビタキ", category: "鳥", image: "images/samebitaki.jpg", tags: ["ヒタキ科"] },
  { id: "kosamebitaki", name: "コサメビタキ", category: "鳥", image: "images/kosamebitaki.jpg", tags: ["ヒタキ科"] },
  { id: "mugimaki", name: "ムギマキ", category: "鳥", image: "images/mugimaki.jpg", tags: ["ヒタキ科"] },
  { id: "nishiojiRobitaki", name: "ニシオジロビタキ", category: "鳥", image: "images/nishiojiRobitaki.jpg", tags: ["ヒタキ科"] },
  // イワヒバリ科（残り）
  { id: "kayakuguri", name: "カヤクグリ", category: "鳥", image: "images/kayakuguri.jpg", tags: ["スズメ目"] },
  // スズメ科（残り）
  { id: "nyuunaIsuzume", name: "ニュウナイスズメ", category: "鳥", image: "images/nyuunaIsuzume.jpg", tags: ["スズメ目"] },
  // カエデチョウ科
  { id: "shimakinpara", name: "シマキンパラ", category: "鳥", image: "images/shimakinpara.jpg", tags: ["外来種"] },
  // セキレイ科（残り）
  { id: "tsumenagasekirei", name: "ツメナガセキレイ", category: "鳥", image: "images/tsumenagasekirei.jpg", tags: ["セキレイ科"] },
  { id: "mamijirotahibari", name: "マミジロタヒバリ", category: "鳥", image: "images/mamijirotahibari.jpg", tags: ["セキレイ科"] },
  { id: "muneakatahibari", name: "ムネアカタヒバリ", category: "鳥", image: "images/muneakatahibari.jpg", tags: ["セキレイ科"] },
  { id: "tahibari", name: "タヒバリ", category: "鳥", image: "images/tahibari.jpg", tags: ["セキレイ科"] },
  // アトリ科（残り）
  { id: "benihiwa", name: "ベニヒワ", category: "鳥", image: "images/benihiwa.jpg", tags: ["アトリ科"] },
  { id: "hagimashiko", name: "ハギマシコ", category: "鳥", image: "images/hagimashiko.jpg", tags: ["アトリ科"] },
  { id: "akamashiko", name: "アカマシコ", category: "鳥", image: "images/akamashiko.jpg", tags: ["アトリ科"] },
  { id: "oomashiko", name: "オオマシコ", category: "鳥", image: "images/oomashiko.jpg", tags: ["アトリ科"] },
  { id: "ginzanmashiko", name: "ギンザンマシコ", category: "鳥", image: "images/ginzanmashiko.jpg", tags: ["アトリ科"] },
  { id: "isuka", name: "イスカ", category: "鳥", image: "images/isuka.jpg", tags: ["アトリ科"] },
  { id: "koikaru", name: "コイカル", category: "鳥", image: "images/koikaru.jpg", tags: ["アトリ科"] },
  // ホオジロ科（残り）
  { id: "tsumenagahoojiro", name: "ツメナガホオジロ", category: "鳥", image: "images/tsumenagahoojiro.jpg", tags: ["ホオジロ科"] },
  { id: "yukihoojiro", name: "ユキホオジロ", category: "鳥", image: "images/yukihoojiro.jpg", tags: ["ホオジロ科"] },
  { id: "hooaka", name: "ホオアカ", category: "鳥", image: "images/hooaka.jpg", tags: ["ホオジロ科"] },
  { id: "kohooaka", name: "コホオアカ", category: "鳥", image: "images/kohooaka.jpg", tags: ["ホオジロ科"] },
  { id: "kimayuhoojiro", name: "キマユホオジロ", category: "鳥", image: "images/kimayuhoojiro.jpg", tags: ["ホオジロ科"] },
  { id: "miyamahoojiro", name: "ミヤマホオジロ", category: "鳥", image: "images/miyamahoojiro.jpg", tags: ["ホオジロ科"] },
  { id: "shimaaoji", name: "シマアオジ", category: "鳥", image: "images/shimaaoji.jpg", tags: ["ホオジロ科"] },
  { id: "nojiko", name: "ノジコ", category: "鳥", image: "images/nojiko.jpg", tags: ["ホオジロ科"] },
  { id: "kuroji", name: "クロジ", category: "鳥", image: "images/kuroji.jpg", tags: ["ホオジロ科"] },
  { id: "kojurin", name: "コジュリン", category: "鳥", image: "images/kojurin.jpg", tags: ["ホオジロ科"] },
];
