const FISH_CREDITS = {
  "hasu": { artist: "Benelli at Japanese Wikipedia", license: "CC BY-SA 3.0" },
  "tsuchifuki": { artist: "Unknown", license: "CC BY-SA 2.5" },
  "mugitsuku": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "kanehira": { artist: "Temminck and Schlegel", license: "Public domain" },
  "shirotanago": { artist: "Daiju Azuma", license: "CC BY 4.0" },
  "yoshinobori_ruisenbo": { artist: "Totti", license: "CC BY-SA 4.0" },
  "bora": { artist: "Diego Delso", license: "CC BY-SA 4.0" },
  "ookuchibasu": { artist: "USFWS Mountain Prairie", license: "Public domain" },
  "kokuchibasu": { artist: "USFWS Mountain Prairie", license: "Public domain" },
  "buruugiru": { artist: "Paleo1954", license: "CC BY-SA 4.0" },
  "channerukyattofisshu": { artist: "USFWS Mountain Prairie", license: "Public domain" },
  "kamuruchii": { artist: "Unknown", license: "Public domain" },
  "nijimasu": { artist: "Engbretson Eric, U.S. Fish and Wildlife Service", license: "Public domain" },
  "ootanago": { artist: "motugon", license: "CC BY-SA 3.0" },
  "sougyou": { artist: "Dezidor", license: "CC BY 3.0" },
  "rengyou": { artist: "USFWS Mountain-Prairie", license: "Public domain" },
  "hakuren": { artist: "USFWS Mountain-Prairie", license: "Public domain" },
  "kokuren": { artist: "Invasive Carp Regional Coordinating Committee", license: "CC BY 2.0" },
  "taiwandojou": { artist: "Meng-Chi Hung", license: "CC BY 4.0" },
  "numagarei": { artist: "Myself", license: "Public domain" },
  "peherey": { artist: "CHUCAO", license: "CC BY-SA 3.0" },
  "gengoroubuna": { artist: "Unknown", license: "CC BY-SA 2.5" },
  "wataka": { artist: "Ffish.asia", license: "CC BY 4.0" },
  "sugomoroko": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "isaza": { artist: "Daiju Azuma", license: "CC BY-SA 4.0" },
  "biwayoshinobori": { artist: "Unknown", license: "CC BY-SA 2.5" },
  "biwakooonamazu": { artist: "KENPEI", license: "CC BY-SA 3.0" },
  "oogarasugomoroko": { artist: "Totti", license: "CC BY-SA 4.0" },
  "ginbuna": { artist: "Unknown", license: "CC BY-SA 2.5" },
  "oikawa": { artist: "Unknown", license: "CC BY-SA 3.0" },
  "kawamutsu": { artist: "Unknown", license: "CC BY-SA 2.5" },
  "numamutsu": { artist: "Ffish.asia", license: "CC BY 4.0" },
  "ugui": { artist: "OpenCage", license: "CC BY-SA 2.5" },
  "nagabuna": { artist: "Ffish.asia", license: "CC BY 4.0" },
  "ichimonjitanago": { artist: "Ffish.asia", license: "CC BY-SA 4.0" },
  "ayu": { artist: "OAS at Japanese Wikipedia", license: "CC BY-SA 3.0" },
  "gigi": { artist: "Totti", license: "CC BY-SA 4.0" },
  "akaza": { artist: "Totti", license: "CC BY-SA 4.0" },
  "ajimedojou": { artist: "Seotaro", license: "CC BY-SA 3.0" },
  "hotokodojou": { artist: "Seotaro", license: "CC BY-SA 3.0" },
  "touyoshinobori": { artist: "book74", license: "CC BY-SA 3.0" },
  "ukigori": { artist: "Seotaro", license: "CC BY-SA 3.0" },
  "sumiukigori": { artist: "Seotaro", license: "CC BY-SA 3.0" },
  "donko": { artist: "Totti", license: "CC BY-SA 4.0" },
  "kajika": { artist: "Seotaro", license: "CC BY-SA 3.0" },
  "amago": { artist: "Alpsdake", license: "CC BY-SA 4.0" },
  "iwana": { artist: "Apple2000", license: "CC BY 3.0" },
  "ooyamato_shimadojou": { artist: "Totti", license: "CC BY-SA 4.0" },
  "tomiyo": { artist: "Piet Spaans", license: "Public domain" },
  "hariyo": { artist: "Alpsdake", license: "CC BY-SA 3.0" },
  "sayori": { artist: "SEFSC Pascagoula Laboratory; Collection of Brandi Noble, NOAA/NMFS/SEFSC NOAA Photo Library", license: "Public domain" },
  "hiuo": { artist: "OAS at Japanese Wikipedia", license: "CC BY-SA 3.0" },
  "shirauo": { artist: "Dmitrismirnov", license: "CC BY-SA 3.0" },
  "tairikubaratanago": { artist: "book74", license: "CC BY-SA 3.0" },
};
