// 昆虫と食草ハンドブック — 全種データ
// INSECT_DATA: 昆虫データ（~95種）
// PLANT_DATA: 食草データ（~100種）

const INSECT_DATA = [
  // ===== チョウ類 - アゲハチョウ科 =====
  { id: "ageha", name: "アゲハ（ナミアゲハ）", category: "チョウ類", image: "images/shokusou/ageha.jpg", foodPlants: ["ミカン類", "サンショウ", "カラタチ", "カラスザンショウ"] },
  { id: "kuroageha", name: "クロアゲハ", category: "チョウ類", image: "images/shokusou/kuroageha.jpg", foodPlants: ["ミカン類", "カラスザンショウ", "コクサギ", "キハダ"] },
  { id: "karasuageha", name: "カラスアゲハ", category: "チョウ類", image: "images/shokusou/karasuageha.jpg", foodPlants: ["コクサギ", "キハダ", "カラスザンショウ"] },
  { id: "nagasakiageha", name: "ナガサキアゲハ", category: "チョウ類", image: "images/shokusou/nagasakiageha.jpg", foodPlants: ["ミカン類", "ユズ", "カラタチ"] },
  { id: "kiageha", name: "キアゲハ", category: "チョウ類", image: "images/shokusou/kiageha.jpg", foodPlants: ["セリ", "ニンジン", "ミツバ"] },
  { id: "aosujiageha", name: "アオスジアゲハ", category: "チョウ類", image: "images/shokusou/aosujiageha.jpg", foodPlants: ["クスノキ", "タブノキ"] },
  { id: "jakouageha", name: "ジャコウアゲハ", category: "チョウ類", image: "images/shokusou/jakouageha.jpg", foodPlants: ["ウマノスズクサ類"] },
  { id: "gifuchou", name: "ギフチョウ", category: "チョウ類", image: "images/shokusou/gifuchou.jpg", foodPlants: ["カンアオイ類"] },

  // ===== チョウ類 - シロチョウ科 =====
  { id: "monshirochou", name: "モンシロチョウ", category: "チョウ類", image: "images/shokusou/monshirochou.jpg", foodPlants: ["キャベツ", "アブラナ類", "イヌガラシ"] },
  { id: "monkichou", name: "モンキチョウ", category: "チョウ類", image: "images/shokusou/monkichou.jpg", foodPlants: ["シロツメクサ"] },
  { id: "kitakichou", name: "キタキチョウ", category: "チョウ類", image: "images/shokusou/kitakichou.jpg", foodPlants: ["ハギ類", "ネムノキ", "メドハギ"] },

  // ===== チョウ類 - タテハチョウ科 =====
  { id: "akatateha", name: "アカタテハ", category: "チョウ類", image: "images/shokusou/akatateha.jpg", foodPlants: ["カラムシ", "アカソ類"] },
  { id: "ruritateha", name: "ルリタテハ", category: "チョウ類", image: "images/shokusou/ruritateha.jpg", foodPlants: ["サルトリイバラ", "ホトトギス類"] },
  { id: "kitateha", name: "キタテハ", category: "チョウ類", image: "images/shokusou/kitateha.jpg", foodPlants: ["カナムグラ"] },
  { id: "tsumagurohyoumon", name: "ツマグロヒョウモン", category: "チョウ類", image: "images/shokusou/tsumagurohyoumon.jpg", foodPlants: ["スミレ類"] },
  { id: "ichimonjichou", name: "イチモンジチョウ", category: "チョウ類", image: "images/shokusou/ichimonjichou.jpg", foodPlants: ["スイカズラ"] },
  { id: "oomurasaki", name: "オオムラサキ", category: "チョウ類", image: "images/shokusou/oomurasaki.jpg", foodPlants: ["エノキ"] },
  { id: "gomadarachou", name: "ゴマダラチョウ", category: "チョウ類", image: "images/shokusou/gomadarachou.jpg", foodPlants: ["エノキ"] },
  { id: "komurasaki", name: "コムラサキ", category: "チョウ類", image: "images/shokusou/komurasaki.jpg", foodPlants: ["ヤナギ類"] },
  { id: "ishigakechou", name: "イシガケチョウ", category: "チョウ類", image: "images/shokusou/ishigakechou.jpg", foodPlants: ["イヌビワ"] },
  { id: "kurokonomachou", name: "クロコノマチョウ", category: "チョウ類", image: "images/shokusou/kurokonomachou.jpg", foodPlants: ["ジュズダマ", "ススキ"] },
  { id: "asagimadara", name: "アサギマダラ", category: "チョウ類", image: "images/shokusou/asagimadara.jpg", foodPlants: ["キジョラン", "イケマ"] },

  // ===== チョウ類 - シジミチョウ科 =====
  { id: "komisuji", name: "コミスジ", category: "チョウ類", image: "images/shokusou/komisuji.jpg", foodPlants: ["クズ", "フジ"] },
  { id: "uraginshijimi", name: "ウラギンシジミ", category: "チョウ類", image: "images/shokusou/uraginshijimi.jpg", foodPlants: ["フジ", "クズ"] },
  { id: "murasakitsubame", name: "ムラサキツバメ", category: "チョウ類", image: "images/shokusou/murasakitsubame.jpg", foodPlants: ["マテバシイ"] },
  { id: "murasakishijimi", name: "ムラサキシジミ", category: "チョウ類", image: "images/shokusou/murasakishijimi.jpg", foodPlants: ["アラカシ", "シラカシ"] },
  { id: "midorishijimi", name: "ミドリシジミ", category: "チョウ類", image: "images/shokusou/midorishijimi.jpg", foodPlants: ["ハンノキ", "ヤマハンノキ"] },
  { id: "yamatoshijimi", name: "ヤマトシジミ", category: "チョウ類", image: "images/shokusou/yamatoshijimi.jpg", foodPlants: ["カタバミ"] },
  { id: "benishijimi", name: "ベニシジミ", category: "チョウ類", image: "images/shokusou/benishijimi.jpg", foodPlants: ["ギシギシ類", "スイバ"] },

  // ===== チョウ類 - セセリチョウ科 =====
  { id: "aobaseseri", name: "アオバセセリ", category: "チョウ類", image: "images/shokusou/aobaseseri.jpg", foodPlants: ["アワブキ"] },
  { id: "suminagashi", name: "スミナガシ", category: "チョウ類", image: "images/shokusou/suminagashi.jpg", foodPlants: ["アワブキ"] },
  { id: "daimyouseseri", name: "ダイミョウセセリ", category: "チョウ類", image: "images/shokusou/daimyouseseri.jpg", foodPlants: ["ヤマノイモ", "オニドコロ"] },
  { id: "ichimonjiseseri", name: "イチモンジセセリ", category: "チョウ類", image: "images/shokusou/ichimonjiseseri.jpg", foodPlants: ["ススキ", "イネ"] },

  // ===== ガ類 =====
  { id: "hotaruga", name: "ホタルガ", category: "ガ類", image: "images/shokusou/hotaruga.jpg", foodPlants: ["ヒサカキ", "サカキ"] },
  { id: "okinawaruri_chirashi", name: "オキナワルリチラシ", category: "ガ類", image: "images/shokusou/okinawaruri_chirashi.jpg", foodPlants: ["ヒサカキ", "サカキ", "ヤブツバキ"] },
  { id: "minousuba", name: "ミノウスバ", category: "ガ類", image: "images/shokusou/minousuba.jpg", foodPlants: ["マサキ", "ニシキギ", "マユミ"] },
  { id: "ibotaga", name: "イボタガ", category: "ガ類", image: "images/shokusou/ibotaga.jpg", foodPlants: ["イボタノキ", "ネズミモチ"] },
  { id: "kiedashaku", name: "キエダシャク", category: "ガ類", image: "images/shokusou/kiedashaku.jpg", foodPlants: ["ノイバラ"] },
  { id: "ooayashaku", name: "オオアヤシャク", category: "ガ類", image: "images/shokusou/ooayashaku.jpg", foodPlants: ["コブシ", "ホオノキ"] },
  { id: "oosukashiba", name: "オオスカシバ", category: "ガ類", image: "images/shokusou/oosukashiba.jpg", foodPlants: ["クチナシ"] },
  { id: "hoshihoujaku", name: "ホシホウジャク", category: "ガ類", image: "images/shokusou/hoshihoujaku.jpg", foodPlants: ["ヘクソカズラ"] },
  { id: "kosuzume", name: "コスズメ", category: "ガ類", image: "images/shokusou/kosuzume.jpg", foodPlants: ["ヤブガラシ"] },
  { id: "kuwaedashaku", name: "クワエダシャク", category: "ガ類", image: "images/shokusou/kuwaedashaku.jpg", foodPlants: ["クワ類"] },
  { id: "monhosobasuzume", name: "モンホソバスズメ", category: "ガ類", image: "images/shokusou/monhosobasuzume.jpg", foodPlants: ["オニグルミ"] },
  { id: "murasakishachihoko", name: "ムラサキシャチホコ", category: "ガ類", image: "images/shokusou/murasakishachihoko.jpg", foodPlants: ["オニグルミ"] },
  { id: "ashibenikagiba", name: "アシベニカギバ", category: "ガ類", image: "images/shokusou/ashibenikagiba.jpg", foodPlants: ["ガマズミ", "サンゴジュ"] },
  { id: "shinjusan", name: "シンジュサン", category: "ガ類", image: "images/shokusou/shinjusan.jpg", foodPlants: ["クロガネモチ", "クスノキ", "クヌギ"] },
  { id: "usutabiga", name: "ウスタビガ", category: "ガ類", image: "images/shokusou/usutabiga.jpg", foodPlants: ["コナラ", "クヌギ", "サクラ類"] },
  { id: "yamamayu", name: "ヤママユ（ヤママユガ）", category: "ガ類", image: "images/shokusou/yamamayu.jpg", foodPlants: ["クヌギ", "コナラ", "クリ"] },
  { id: "takekareha", name: "タケカレハ", category: "ガ類", image: "images/shokusou/takekareha.jpg", foodPlants: ["タケ類", "ササ類"] },
  { id: "takenohosokuroba", name: "タケノホソクロバ", category: "ガ類", image: "images/shokusou/takenohosokuroba.jpg", foodPlants: ["タケ類", "ササ類"] },
  { id: "matsukareha", name: "マツカレハ", category: "ガ類", image: "images/shokusou/matsukareha.jpg", foodPlants: ["マツ類"] },
  { id: "chadokuga", name: "チャドクガ", category: "ガ類", image: "images/shokusou/chadokuga.jpg", foodPlants: ["ツバキ類", "サザンカ"] },
  { id: "kinokawaga", name: "キノカワガ", category: "ガ類", image: "images/shokusou/kinokawaga.jpg", foodPlants: ["カキノキ"] },
  { id: "oogomadara_edashaku", name: "オオゴマダラエダシャク", category: "ガ類", image: "images/shokusou/oogomadara_edashaku.jpg", foodPlants: ["カキノキ"] },
  { id: "iraga", name: "イラガ", category: "ガ類", image: "images/shokusou/iraga.jpg", foodPlants: ["カキノキ", "サクラ類", "クリ"] },
  { id: "akebikonoha", name: "アケビコノハ", category: "ガ類", image: "images/shokusou/akebikonoha.jpg", foodPlants: ["アケビ", "ミツバアケビ"] },
  { id: "oomizuao", name: "オオミズアオ", category: "ガ類", image: "images/shokusou/oomizuao.jpg", foodPlants: ["サクラ類", "クリ", "ハナミズキ"] },
  { id: "kususan", name: "クスサン", category: "ガ類", image: "images/shokusou/kususan.jpg", foodPlants: ["クリ", "サクラ類", "クスノキ", "ケヤキ"] },
  { id: "maimaiga", name: "マイマイガ", category: "ガ類", image: "images/shokusou/maimaiga.jpg", foodPlants: ["サクラ類", "クヌギ", "ケヤキ"] },

  // ===== 甲虫類 =====
  { id: "gomadarakamikiri", name: "ゴマダラカミキリ", category: "甲虫類", image: "images/shokusou/gomadarakamikiri.jpg", foodPlants: ["ヤナギ類", "ミカン類", "スズカケノキ類"] },
  { id: "kuwakamikiri", name: "クワカミキリ", category: "甲虫類", image: "images/shokusou/kuwakamikiri.jpg", foodPlants: ["イチジク", "クワ類", "ケヤキ"] },
  { id: "nijuuyahoshi_tentou", name: "ニジュウヤホシテントウ", category: "甲虫類", image: "images/shokusou/nijuuyahoshi_tentou.jpg", foodPlants: ["イヌホオズキ類"] },
  { id: "tohoshi_tentou", name: "トホシテントウ", category: "甲虫類", image: "images/shokusou/tohoshi_tentou.jpg", foodPlants: ["カラスウリ"] },
  { id: "jingasahamushi", name: "ジンガサハムシ", category: "甲虫類", image: "images/shokusou/jingasahamushi.jpg", foodPlants: ["ヒルガオ"] },
  { id: "ichimonji_kamenokohamushi", name: "イチモンジカメノコハムシ", category: "甲虫類", image: "images/shokusou/ichimonji_kamenokohamushi.jpg", foodPlants: ["ムラサキシキブ"] },
  { id: "tohoshi_kubibosohamushi", name: "トホシクビボソハムシ", category: "甲虫類", image: "images/shokusou/tohoshi_kubibosohamushi.jpg", foodPlants: ["クコ"] },
  { id: "nirehamushi", name: "ニレハムシ", category: "甲虫類", image: "images/shokusou/nirehamushi.jpg", foodPlants: ["ケヤキ", "アキニレ"] },
  { id: "tsutsuji_kobuhamushi", name: "ツツジコブハムシ", category: "甲虫類", image: "images/shokusou/tsutsuji_kobuhamushi.jpg", foodPlants: ["ツツジ類"] },
  { id: "akagane_saruhamushi", name: "アカガネサルハムシ", category: "甲虫類", image: "images/shokusou/akagane_saruhamushi.jpg", foodPlants: ["エビヅル", "ノブドウ"] },
  { id: "heriguro_tentouno_mihamushi", name: "ヘリグロテントウノミハムシ", category: "甲虫類", image: "images/shokusou/heriguro_tentouno_mihamushi.jpg", foodPlants: ["ヒイラギモクセイ", "ヒイラギ"] },
  { id: "drohamaki_chokkiri", name: "ドロハマキチョッキリ", category: "甲虫類", image: "images/shokusou/drohamaki_chokkiri.jpg", foodPlants: ["イタドリ"] },
  { id: "higenaga_otoshibumi", name: "ヒゲナガオトシブミ", category: "甲虫類", image: "images/shokusou/higenaga_otoshibumi.jpg", foodPlants: ["アブラチャン", "クロモジ"] },
  { id: "otoshibumi", name: "オトシブミ（ナミオトシブミ）", category: "甲虫類", image: "images/shokusou/otoshibumi.jpg", foodPlants: ["クリ", "コナラ", "ハンノキ"] },
  { id: "shirosuji_kamikiri", name: "シロスジカミキリ", category: "甲虫類", image: "images/shokusou/shirosuji_kamikiri.jpg", foodPlants: ["クリ", "コナラ", "クヌギ"] },
  { id: "ego_higenaga_zoumushi", name: "エゴヒゲナガゾウムシ", category: "甲虫類", image: "images/shokusou/ego_higenaga_zoumushi.jpg", foodPlants: ["エゴノキ"] },
  { id: "ego_tsurukubi_otoshibumi", name: "エゴツルクビオトシブミ", category: "甲虫類", image: "images/shokusou/ego_tsurukubi_otoshibumi.jpg", foodPlants: ["エゴノキ"] },

  // ===== カメムシ類 =====
  { id: "akasuji_kamemushi", name: "アカスジカメムシ", category: "カメムシ類", image: "images/shokusou/akasuji_kamemushi.jpg", foodPlants: ["ヤブジラミ", "ニンジン"] },
  { id: "kibara_herikamemushi", name: "キバラヘリカメムシ", category: "カメムシ類", image: "images/shokusou/kibara_herikamemushi.jpg", foodPlants: ["マユミ", "ニシキギ"] },
  { id: "esaki_monki_tsunokamemushi", name: "エサキモンキツノカメムシ", category: "カメムシ類", image: "images/shokusou/esaki_monki_tsunokamemushi.jpg", foodPlants: ["ミズキ", "ハンノキ"] },
  { id: "akasuji_kinkamemushi", name: "アカスジキンカメムシ", category: "カメムシ類", image: "images/shokusou/akasuji_kinkamemushi.jpg", foodPlants: ["ミズキ", "コブシ"] },
  { id: "ookin_kamemushi", name: "オオキンカメムシ", category: "カメムシ類", image: "images/shokusou/ookin_kamemushi.jpg", foodPlants: ["アブラギリ"] },
  { id: "akagi_kamemushi", name: "アカギカメムシ", category: "カメムシ類", image: "images/shokusou/akagi_kamemushi.jpg", foodPlants: ["アカメガシワ"] },

  // ===== 沖縄チョウ =====
  { id: "shiroobi_ageha", name: "シロオビアゲハ", category: "沖縄チョウ", image: "images/shokusou/shiroobi_ageha.jpg", foodPlants: ["シークワーサー"] },
  { id: "tsumabeni_chou", name: "ツマベニチョウ", category: "沖縄チョウ", image: "images/shokusou/tsumabeni_chou.jpg", foodPlants: ["ギョボク"] },
  { id: "namie_shirochou", name: "ナミエシロチョウ", category: "沖縄チョウ", image: "images/shokusou/namie_shirochou.jpg", foodPlants: ["ツゲモドキ"] },
  { id: "oogomadara", name: "オオゴマダラ", category: "沖縄チョウ", image: "images/shokusou/oogomadara.jpg", foodPlants: ["ホウライカガミ"] },
  { id: "kabamadara", name: "カバマダラ", category: "沖縄チョウ", image: "images/shokusou/kabamadara.jpg", foodPlants: ["トウワタ"] },
  { id: "tsumamurasakimadara", name: "ツマムラサキマダラ", category: "沖縄チョウ", image: "images/shokusou/tsumamurasakimadara.jpg", foodPlants: ["オキナワテイカカズラ"] },
  { id: "ryuukyuu_asagimadara", name: "リュウキュウアサギマダラ", category: "沖縄チョウ", image: "images/shokusou/ryuukyuu_asagimadara.jpg", foodPlants: ["ツルモウリンカ"] },
  { id: "konohachou", name: "コノハチョウ", category: "沖縄チョウ", image: "images/shokusou/konohachou.jpg", foodPlants: ["オキナワスズムシソウ"] },
  { id: "aotateha_modoki", name: "アオタテハモドキ", category: "沖縄チョウ", image: "images/shokusou/aotateha_modoki.jpg", foodPlants: ["イワダレソウ"] },
  { id: "iwakawa_shijimi", name: "イワカワシジミ", category: "沖縄チョウ", image: "images/shokusou/iwakawa_shijimi.jpg", foodPlants: ["クチナシ"] },
  { id: "banana_seseri", name: "バナナセセリ", category: "沖縄チョウ", image: "images/shokusou/banana_seseri.jpg", foodPlants: ["バナナ"] },
];

const PLANT_DATA = [
  // ===== 樹木 =====
  { id: "mikan_rui", name: "ミカン類", category: "樹木", image: "images/shokusou/mikan_rui.jpg", insects: ["アゲハ（ナミアゲハ）", "クロアゲハ", "ナガサキアゲハ", "ゴマダラカミキリ"] },
  { id: "sanshou", name: "サンショウ", category: "樹木", image: "images/shokusou/sanshou.jpg", insects: ["アゲハ（ナミアゲハ）"] },
  { id: "karatachi", name: "カラタチ", category: "樹木", image: "images/shokusou/karatachi.jpg", insects: ["アゲハ（ナミアゲハ）", "ナガサキアゲハ"] },
  { id: "karasuzanshou", name: "カラスザンショウ", category: "樹木", image: "images/shokusou/karasuzanshou.jpg", insects: ["アゲハ（ナミアゲハ）", "クロアゲハ", "カラスアゲハ"] },
  { id: "kokusagi", name: "コクサギ", category: "樹木", image: "images/shokusou/kokusagi.jpg", insects: ["クロアゲハ", "カラスアゲハ"] },
  { id: "kihada", name: "キハダ", category: "樹木", image: "images/shokusou/kihada.jpg", insects: ["クロアゲハ", "カラスアゲハ"] },
  { id: "yuzu", name: "ユズ", category: "樹木", image: "images/shokusou/yuzu.jpg", insects: ["ナガサキアゲハ"] },
  { id: "kusunoki", name: "クスノキ", category: "樹木", image: "images/shokusou/kusunoki.jpg", insects: ["アオスジアゲハ", "シンジュサン", "クスサン"] },
  { id: "tabunoki", name: "タブノキ", category: "樹木", image: "images/shokusou/tabunoki.jpg", insects: ["アオスジアゲハ"] },
  { id: "hagi_rui", name: "ハギ類", category: "樹木", image: "images/shokusou/hagi_rui.jpg", insects: ["キタキチョウ"] },
  { id: "nemunoki", name: "ネムノキ", category: "樹木", image: "images/shokusou/nemunoki.jpg", insects: ["キタキチョウ"] },
  { id: "sarutoriibara", name: "サルトリイバラ", category: "樹木", image: "images/shokusou/sarutoriibara.jpg", insects: ["ルリタテハ"] },
  { id: "suikazura", name: "スイカズラ", category: "樹木", image: "images/shokusou/suikazura.jpg", insects: ["イチモンジチョウ"] },
  { id: "enoki", name: "エノキ", category: "樹木", image: "images/shokusou/enoki.jpg", insects: ["オオムラサキ", "ゴマダラチョウ"] },
  { id: "yanagi_rui", name: "ヤナギ類", category: "樹木", image: "images/shokusou/yanagi_rui.jpg", insects: ["コムラサキ", "ゴマダラカミキリ"] },
  { id: "inubiwa", name: "イヌビワ", category: "樹木", image: "images/shokusou/inubiwa.jpg", insects: ["イシガケチョウ"] },
  { id: "fuji", name: "フジ", category: "樹木", image: "images/shokusou/fuji.jpg", insects: ["コミスジ", "ウラギンシジミ"] },
  { id: "matebashii", name: "マテバシイ", category: "樹木", image: "images/shokusou/matebashii.jpg", insects: ["ムラサキツバメ"] },
  { id: "arakashi", name: "アラカシ", category: "樹木", image: "images/shokusou/arakashi.jpg", insects: ["ムラサキシジミ"] },
  { id: "shirakashi", name: "シラカシ", category: "樹木", image: "images/shokusou/shirakashi.jpg", insects: ["ムラサキシジミ"] },
  { id: "hannoki", name: "ハンノキ", category: "樹木", image: "images/shokusou/hannoki.jpg", insects: ["ミドリシジミ", "エサキモンキツノカメムシ", "オトシブミ（ナミオトシブミ）"] },
  { id: "yamahannoki", name: "ヤマハンノキ", category: "樹木", image: "images/shokusou/yamahannoki.jpg", insects: ["ミドリシジミ"] },
  { id: "awabuki", name: "アワブキ", category: "樹木", image: "images/shokusou/awabuki.jpg", insects: ["アオバセセリ", "スミナガシ"] },
  { id: "hisakaki", name: "ヒサカキ", category: "樹木", image: "images/shokusou/hisakaki.jpg", insects: ["ホタルガ", "オキナワルリチラシ"] },
  { id: "sakaki", name: "サカキ", category: "樹木", image: "images/shokusou/sakaki.jpg", insects: ["ホタルガ", "オキナワルリチラシ"] },
  { id: "yabutsubaki", name: "ヤブツバキ", category: "樹木", image: "images/shokusou/yabutsubaki.jpg", insects: ["オキナワルリチラシ"] },
  { id: "masaki", name: "マサキ", category: "樹木", image: "images/shokusou/masaki.jpg", insects: ["ミノウスバ"] },
  { id: "nishikigi", name: "ニシキギ", category: "樹木", image: "images/shokusou/nishikigi.jpg", insects: ["ミノウスバ", "キバラヘリカメムシ"] },
  { id: "mayumi", name: "マユミ", category: "樹木", image: "images/shokusou/mayumi.jpg", insects: ["ミノウスバ", "キバラヘリカメムシ"] },
  { id: "ibotanoki", name: "イボタノキ", category: "樹木", image: "images/shokusou/ibotanoki.jpg", insects: ["イボタガ"] },
  { id: "nezumimochi", name: "ネズミモチ", category: "樹木", image: "images/shokusou/nezumimochi.jpg", insects: ["イボタガ"] },
  { id: "noibara", name: "ノイバラ", category: "樹木", image: "images/shokusou/noibara.jpg", insects: ["キエダシャク"] },
  { id: "kobushi", name: "コブシ", category: "樹木", image: "images/shokusou/kobushi.jpg", insects: ["オオアヤシャク", "アカスジキンカメムシ"] },
  { id: "hoonoki", name: "ホオノキ", category: "樹木", image: "images/shokusou/hoonoki.jpg", insects: ["オオアヤシャク"] },
  { id: "kuchinashi", name: "クチナシ", category: "樹木", image: "images/shokusou/kuchinashi.jpg", insects: ["オオスカシバ", "イワカワシジミ"] },
  { id: "kuwa_rui", name: "クワ類", category: "樹木", image: "images/shokusou/kuwa_rui.jpg", insects: ["クワエダシャク", "クワカミキリ"] },
  { id: "onigurumi", name: "オニグルミ", category: "樹木", image: "images/shokusou/onigurumi.jpg", insects: ["モンホソバスズメ", "ムラサキシャチホコ"] },
  { id: "gamazumi", name: "ガマズミ", category: "樹木", image: "images/shokusou/gamazumi.jpg", insects: ["アシベニカギバ"] },
  { id: "sangoju", name: "サンゴジュ", category: "樹木", image: "images/shokusou/sangoju.jpg", insects: ["アシベニカギバ"] },
  { id: "kuroganemochi", name: "クロガネモチ", category: "樹木", image: "images/shokusou/kuroganemochi.jpg", insects: ["シンジュサン"] },
  { id: "konara", name: "コナラ", category: "樹木", image: "images/shokusou/konara.jpg", insects: ["ウスタビガ", "ヤママユ（ヤママユガ）", "シロスジカミキリ", "オトシブミ（ナミオトシブミ）"] },
  { id: "kunugi", name: "クヌギ", category: "樹木", image: "images/shokusou/kunugi.jpg", insects: ["ウスタビガ", "ヤママユ（ヤママユガ）", "シンジュサン", "マイマイガ", "シロスジカミキリ"] },
  { id: "kuri", name: "クリ", category: "樹木", image: "images/shokusou/kuri.jpg", insects: ["ヤママユ（ヤママユガ）", "イラガ", "オオミズアオ", "クスサン", "オトシブミ（ナミオトシブミ）", "シロスジカミキリ"] },
  { id: "sakura_rui", name: "サクラ類", category: "樹木", image: "images/shokusou/sakura_rui.jpg", insects: ["ウスタビガ", "イラガ", "オオミズアオ", "クスサン", "マイマイガ"] },
  { id: "take_rui", name: "タケ類", category: "樹木", image: "images/shokusou/take_rui.jpg", insects: ["タケカレハ", "タケノホソクロバ"] },
  { id: "matsu_rui", name: "マツ類", category: "樹木", image: "images/shokusou/matsu_rui.jpg", insects: ["マツカレハ"] },
  { id: "tsubaki_rui", name: "ツバキ類", category: "樹木", image: "images/shokusou/tsubaki_rui.jpg", insects: ["チャドクガ"] },
  { id: "sazanka", name: "サザンカ", category: "樹木", image: "images/shokusou/sazanka.jpg", insects: ["チャドクガ"] },
  { id: "kakinoki", name: "カキノキ", category: "樹木", image: "images/shokusou/kakinoki.jpg", insects: ["キノカワガ", "オオゴマダラエダシャク", "イラガ"] },
  { id: "akebi", name: "アケビ", category: "樹木", image: "images/shokusou/akebi.jpg", insects: ["アケビコノハ"] },
  { id: "mitsubaakebi", name: "ミツバアケビ", category: "樹木", image: "images/shokusou/mitsubaakebi.jpg", insects: ["アケビコノハ"] },
  { id: "hanamizuki", name: "ハナミズキ", category: "樹木", image: "images/shokusou/hanamizuki.jpg", insects: ["オオミズアオ"] },
  { id: "keyaki", name: "ケヤキ", category: "樹木", image: "images/shokusou/keyaki.jpg", insects: ["ニレハムシ", "クワカミキリ", "クスサン", "マイマイガ"] },
  { id: "akinire", name: "アキニレ", category: "樹木", image: "images/shokusou/akinire.jpg", insects: ["ニレハムシ"] },
  { id: "ichijiku", name: "イチジク", category: "樹木", image: "images/shokusou/ichijiku.jpg", insects: ["クワカミキリ"] },
  { id: "suzukakenoki_rui", name: "スズカケノキ類", category: "樹木", image: "images/shokusou/suzukakenoki_rui.jpg", insects: ["ゴマダラカミキリ"] },
  { id: "murasakishikibu", name: "ムラサキシキブ", category: "樹木", image: "images/shokusou/murasakishikibu.jpg", insects: ["イチモンジカメノコハムシ"] },
  { id: "kuko", name: "クコ", category: "樹木", image: "images/shokusou/kuko.jpg", insects: ["トホシクビボソハムシ"] },
  { id: "tsutsuji_rui", name: "ツツジ類", category: "樹木", image: "images/shokusou/tsutsuji_rui.jpg", insects: ["ツツジコブハムシ"] },
  { id: "hiiragi_mokusei", name: "ヒイラギモクセイ", category: "樹木", image: "images/shokusou/hiiragi_mokusei.jpg", insects: ["ヘリグロテントウノミハムシ"] },
  { id: "hiiragi", name: "ヒイラギ", category: "樹木", image: "images/shokusou/hiiragi.jpg", insects: ["ヘリグロテントウノミハムシ"] },
  { id: "aburachan", name: "アブラチャン", category: "樹木", image: "images/shokusou/aburachan.jpg", insects: ["ヒゲナガオトシブミ"] },
  { id: "kuromoji", name: "クロモジ", category: "樹木", image: "images/shokusou/kuromoji.jpg", insects: ["ヒゲナガオトシブミ"] },
  { id: "egonoki", name: "エゴノキ", category: "樹木", image: "images/shokusou/egonoki.jpg", insects: ["エゴヒゲナガゾウムシ", "エゴツルクビオトシブミ"] },
  { id: "mizuki", name: "ミズキ", category: "樹木", image: "images/shokusou/mizuki.jpg", insects: ["エサキモンキツノカメムシ", "アカスジキンカメムシ"] },
  { id: "aburagiri", name: "アブラギリ", category: "樹木", image: "images/shokusou/aburagiri.jpg", insects: ["オオキンカメムシ"] },
  { id: "akamegashiwa", name: "アカメガシワ", category: "樹木", image: "images/shokusou/akamegashiwa.jpg", insects: ["アカギカメムシ"] },
  { id: "shiikuwaasaa", name: "シークワーサー", category: "樹木", image: "images/shokusou/shiikuwaasaa.jpg", insects: ["シロオビアゲハ"] },
  { id: "gyoboku", name: "ギョボク", category: "樹木", image: "images/shokusou/gyoboku.jpg", insects: ["ツマベニチョウ"] },
  { id: "tsugemodoki", name: "ツゲモドキ", category: "樹木", image: "images/shokusou/tsugemodoki.jpg", insects: ["ナミエシロチョウ"] },
  { id: "hourai_kagami", name: "ホウライカガミ", category: "樹木", image: "images/shokusou/hourai_kagami.jpg", insects: ["オオゴマダラ"] },
  { id: "okinawa_teikakazura", name: "オキナワテイカカズラ", category: "樹木", image: "images/shokusou/okinawa_teikakazura.jpg", insects: ["ツマムラサキマダラ"] },

  // ===== 草本 =====
  { id: "seri", name: "セリ", category: "草本", image: "images/shokusou/seri.jpg", insects: ["キアゲハ"] },
  { id: "ninjin", name: "ニンジン", category: "草本", image: "images/shokusou/ninjin.jpg", insects: ["キアゲハ", "アカスジカメムシ"] },
  { id: "mitsuba", name: "ミツバ", category: "草本", image: "images/shokusou/mitsuba.jpg", insects: ["キアゲハ"] },
  { id: "umanosuzukusa_rui", name: "ウマノスズクサ類", category: "草本", image: "images/shokusou/umanosuzukusa_rui.jpg", insects: ["ジャコウアゲハ"] },
  { id: "kanaoi_rui", name: "カンアオイ類", category: "草本", image: "images/shokusou/kanaoi_rui.jpg", insects: ["ギフチョウ"] },
  { id: "kyabetsu", name: "キャベツ", category: "草本", image: "images/shokusou/kyabetsu.jpg", insects: ["モンシロチョウ"] },
  { id: "aburana_rui", name: "アブラナ類", category: "草本", image: "images/shokusou/aburana_rui.jpg", insects: ["モンシロチョウ"] },
  { id: "inugarashi", name: "イヌガラシ", category: "草本", image: "images/shokusou/inugarashi.jpg", insects: ["モンシロチョウ"] },
  { id: "shirotsumekusa", name: "シロツメクサ", category: "草本", image: "images/shokusou/shirotsumekusa.jpg", insects: ["モンキチョウ"] },
  { id: "medohagi", name: "メドハギ", category: "草本", image: "images/shokusou/medohagi.jpg", insects: ["キタキチョウ"] },
  { id: "karamushi", name: "カラムシ", category: "草本", image: "images/shokusou/karamushi.jpg", insects: ["アカタテハ"] },
  { id: "akaso_rui", name: "アカソ類", category: "草本", image: "images/shokusou/akaso_rui.jpg", insects: ["アカタテハ"] },
  { id: "hototogisu_rui", name: "ホトトギス類", category: "草本", image: "images/shokusou/hototogisu_rui.jpg", insects: ["ルリタテハ"] },
  { id: "kanamugura", name: "カナムグラ", category: "草本", image: "images/shokusou/kanamugura.jpg", insects: ["キタテハ"] },
  { id: "sumire_rui", name: "スミレ類", category: "草本", image: "images/shokusou/sumire_rui.jpg", insects: ["ツマグロヒョウモン"] },
  { id: "juzudama", name: "ジュズダマ", category: "草本", image: "images/shokusou/juzudama.jpg", insects: ["クロコノマチョウ"] },
  { id: "susuki", name: "ススキ", category: "草本", image: "images/shokusou/susuki.jpg", insects: ["クロコノマチョウ", "イチモンジセセリ"] },
  { id: "kijoran", name: "キジョラン", category: "草本", image: "images/shokusou/kijoran.jpg", insects: ["アサギマダラ"] },
  { id: "ikema", name: "イケマ", category: "草本", image: "images/shokusou/ikema.jpg", insects: ["アサギマダラ"] },
  { id: "kuzu", name: "クズ", category: "草本", image: "images/shokusou/kuzu.jpg", insects: ["コミスジ", "ウラギンシジミ"] },
  { id: "katabami", name: "カタバミ", category: "草本", image: "images/shokusou/katabami.jpg", insects: ["ヤマトシジミ"] },
  { id: "gishigishi_rui", name: "ギシギシ類", category: "草本", image: "images/shokusou/gishigishi_rui.jpg", insects: ["ベニシジミ"] },
  { id: "suiba", name: "スイバ", category: "草本", image: "images/shokusou/suiba.jpg", insects: ["ベニシジミ"] },
  { id: "yamanoimo", name: "ヤマノイモ", category: "草本", image: "images/shokusou/yamanoimo.jpg", insects: ["ダイミョウセセリ"] },
  { id: "onidokoro", name: "オニドコロ", category: "草本", image: "images/shokusou/onidokoro.jpg", insects: ["ダイミョウセセリ"] },
  { id: "ine", name: "イネ", category: "草本", image: "images/shokusou/ine.jpg", insects: ["イチモンジセセリ"] },
  { id: "sasa_rui", name: "ササ類", category: "草本", image: "images/shokusou/sasa_rui.jpg", insects: ["タケカレハ", "タケノホソクロバ"] },
  { id: "hekusokazura", name: "ヘクソカズラ", category: "草本", image: "images/shokusou/hekusokazura.jpg", insects: ["ホシホウジャク"] },
  { id: "yabugarashi", name: "ヤブガラシ", category: "草本", image: "images/shokusou/yabugarashi.jpg", insects: ["コスズメ"] },
  { id: "inuhoozuki_rui", name: "イヌホオズキ類", category: "草本", image: "images/shokusou/inuhoozuki_rui.jpg", insects: ["ニジュウヤホシテントウ"] },
  { id: "karasuuri", name: "カラスウリ", category: "草本", image: "images/shokusou/karasuuri.jpg", insects: ["トホシテントウ"] },
  { id: "hirugao", name: "ヒルガオ", category: "草本", image: "images/shokusou/hirugao.jpg", insects: ["ジンガサハムシ"] },
  { id: "ebizuru", name: "エビヅル", category: "草本", image: "images/shokusou/ebizuru.jpg", insects: ["アカガネサルハムシ"] },
  { id: "nobudou", name: "ノブドウ", category: "草本", image: "images/shokusou/nobudou.jpg", insects: ["アカガネサルハムシ"] },
  { id: "itadori", name: "イタドリ", category: "草本", image: "images/shokusou/itadori.jpg", insects: ["ドロハマキチョッキリ"] },
  { id: "yabujirami", name: "ヤブジラミ", category: "草本", image: "images/shokusou/yabujirami.jpg", insects: ["アカスジカメムシ"] },
  { id: "touwata", name: "トウワタ", category: "草本", image: "images/shokusou/touwata.jpg", insects: ["カバマダラ"] },
  { id: "tsurumourinka", name: "ツルモウリンカ", category: "草本", image: "images/shokusou/tsurumourinka.jpg", insects: ["リュウキュウアサギマダラ"] },
  { id: "okinawa_suzumushisou", name: "オキナワスズムシソウ", category: "草本", image: "images/shokusou/okinawa_suzumushisou.jpg", insects: ["コノハチョウ"] },
  { id: "iwadaresou", name: "イワダレソウ", category: "草本", image: "images/shokusou/iwadaresou.jpg", insects: ["アオタテハモドキ"] },
  { id: "banana", name: "バナナ", category: "草本", image: "images/shokusou/banana.jpg", insects: ["バナナセセリ"] },
];
